# This file is generated by running "yarn install" inside your project.
# It is essentially a version of yarn.lock that Nix can better understand
# Manual changes WILL be lost - proceed with caution!
let
  settings = {
    compressionLevel = "mixed";
  };
  packages = {
    "accepts@npm:1.3.8" = {
      name = "accepts";
      reference = "npm:1.3.8";
      linkType = "HARD";
      outputName = "accepts-1.3.8-9a812371c9";
      outputHash = "67eaaa90e2917c58418e7a9b89392002d2b1ccd69bcca4799135d0c632f3b082f23f4ae4ddeedbced5aa59bcc7bdf4699c69ebed4593696c922462b7bc5744d6";
      flatName = "accepts";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:~1.3.8";
      checksum = "10/67eaaa90e2917c58418e7a9b89392002d2b1ccd69bcca4799135d0c632f3b082f23f4ae4ddeedbced5aa59bcc7bdf4699c69ebed4593696c922462b7bc5744d6";
      dependencies = {
        "mime-types" = packages."mime-types@npm:2.1.35";
        "negotiator" = packages."negotiator@npm:0.6.3";
      };
    };
    "array-flatten@npm:1.1.1" = {
      name = "array-flatten";
      reference = "npm:1.1.1";
      linkType = "HARD";
      outputName = "array-flatten-1.1.1-9d94ad5f1d";
      outputHash = "e13c9d247241be82f8b4ec71d035ed7204baa82fae820d4db6948d30d3c4a9f2b3905eb2eec2b937d4aa3565200bd3a1c500480114cff649fa748747d2a50feb";
      flatName = "array-flatten";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:1.1.1";
      checksum = "10/e13c9d247241be82f8b4ec71d035ed7204baa82fae820d4db6948d30d3c4a9f2b3905eb2eec2b937d4aa3565200bd3a1c500480114cff649fa748747d2a50feb";
    };
    "asynckit@npm:0.4.0" = {
      name = "asynckit";
      reference = "npm:0.4.0";
      linkType = "HARD";
      outputName = "asynckit-0.4.0-c718858525";
      outputHash = "3ce727cbc78f69d6a4722517a58ee926c8c21083633b1d3fdf66fd688f6c127a53a592141bd4866f9b63240a86e9d8e974b13919450bd17fa33c2d22c4558ad8";
      flatName = "asynckit";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^0.4.0";
      checksum = "10/3ce727cbc78f69d6a4722517a58ee926c8c21083633b1d3fdf66fd688f6c127a53a592141bd4866f9b63240a86e9d8e974b13919450bd17fa33c2d22c4558ad8";
    };
    "axios@npm:1.3.2" = {
      name = "axios";
      reference = "npm:1.3.2";
      linkType = "HARD";
      outputName = "axios-1.3.2-e60543899f";
      outputHash = "b6b30c877c768436af66cb98c6280f68fadf7a0fe8ce2453cd9fa1e3d3b29e47ce7c6ca54b477eae3ffea3a672b3dcc9614fab59bc4bb99a8fe02dc1ffd2b30c";
      flatName = "axios";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^1.3.2";
      checksum = "10/b6b30c877c768436af66cb98c6280f68fadf7a0fe8ce2453cd9fa1e3d3b29e47ce7c6ca54b477eae3ffea3a672b3dcc9614fab59bc4bb99a8fe02dc1ffd2b30c";
      dependencies = {
        "form-data" = packages."form-data@npm:4.0.0";
        "proxy-from-env" = packages."proxy-from-env@npm:1.1.0";
        "follow-redirects" = packages."follow-redirects@virtual:e60543899fd705bd5f850d61bc1194b1bf7a80a922cb114420112d5561895397647171575ef119a8decf292183f1806d99bf972caa13adcdef0a1056caa42cb3#npm:1.15.2";
      };
    };
    "body-parser@npm:1.20.1" = {
      name = "body-parser";
      reference = "npm:1.20.1";
      linkType = "HARD";
      outputName = "body-parser-1.20.1-759fd14db9";
      outputHash = "5f8d128022a2fb8b6e7990d30878a0182f300b70e46b3f9d358a9433ad6275f0de46add6d63206da3637c01c3b38b6111a7480f7e7ac2e9f7b989f6133fe5510";
      flatName = "body-parser";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^1.19.0";
      checksum = "10/5f8d128022a2fb8b6e7990d30878a0182f300b70e46b3f9d358a9433ad6275f0de46add6d63206da3637c01c3b38b6111a7480f7e7ac2e9f7b989f6133fe5510";
      dependencies = {
        "bytes" = packages."bytes@npm:3.1.2";
        "content-type" = packages."content-type@npm:1.0.4";
        "depd" = packages."depd@npm:2.0.0";
        "destroy" = packages."destroy@npm:1.2.0";
        "http-errors" = packages."http-errors@npm:2.0.0";
        "iconv-lite" = packages."iconv-lite@npm:0.4.24";
        "on-finished" = packages."on-finished@npm:2.4.1";
        "qs" = packages."qs@npm:6.11.0";
        "raw-body" = packages."raw-body@npm:2.5.1";
        "type-is" = packages."type-is@npm:1.6.18";
        "unpipe" = packages."unpipe@npm:1.0.0";
        "debug" = packages."debug@virtual:759fd14db92b54abdb7afb3d21dbf8d50f1a5c59c96cd3f963ce3e3ed063bdb801142fae5f01cc81fb79f7ddc13b7c31a9deb9d5a9cfa48ec107f83de8f7f40e#npm:2.6.9";
      };
    };
    "bytes@npm:3.1.2" = {
      name = "bytes";
      reference = "npm:3.1.2";
      linkType = "HARD";
      outputName = "bytes-3.1.2-28b8643004";
      outputHash = "a10abf2ba70c784471d6b4f58778c0beeb2b5d405148e66affa91f23a9f13d07603d0a0354667310ae1d6dc141474ffd44e2a074be0f6e2254edb8fc21445388";
      flatName = "bytes";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:3.1.2";
      checksum = "10/a10abf2ba70c784471d6b4f58778c0beeb2b5d405148e66affa91f23a9f13d07603d0a0354667310ae1d6dc141474ffd44e2a074be0f6e2254edb8fc21445388";
    };
    "call-bind@npm:1.0.2" = {
      name = "call-bind";
      reference = "npm:1.0.2";
      linkType = "HARD";
      outputName = "call-bind-1.0.2-c957124861";
      outputHash = "ca787179c1cbe09e1697b56ad499fd05dc0ae6febe5081d728176ade699ea6b1589240cb1ff1fe11fcf9f61538c1af60ad37e8eb2ceb4ef21cd6085dfd3ccedd";
      flatName = "call-bind";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^1.0.0";
      checksum = "10/ca787179c1cbe09e1697b56ad499fd05dc0ae6febe5081d728176ade699ea6b1589240cb1ff1fe11fcf9f61538c1af60ad37e8eb2ceb4ef21cd6085dfd3ccedd";
      dependencies = {
        "function-bind" = packages."function-bind@npm:1.1.1";
        "get-intrinsic" = packages."get-intrinsic@npm:1.2.0";
      };
    };
    "combined-stream@npm:1.0.8" = {
      name = "combined-stream";
      reference = "npm:1.0.8";
      linkType = "HARD";
      outputName = "combined-stream-1.0.8-dc14d4a63a";
      outputHash = "2e969e637d05d09fa50b02d74c83a1186f6914aae89e6653b62595cc75a221464f884f55f231b8f4df7a49537fba60bdc0427acd2bf324c09a1dbb84837e36e4";
      flatName = "combined-stream";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^1.0.8";
      checksum = "10/2e969e637d05d09fa50b02d74c83a1186f6914aae89e6653b62595cc75a221464f884f55f231b8f4df7a49537fba60bdc0427acd2bf324c09a1dbb84837e36e4";
      dependencies = {
        "delayed-stream" = packages."delayed-stream@npm:1.0.0";
      };
    };
    "content-disposition@npm:0.5.4" = {
      name = "content-disposition";
      reference = "npm:0.5.4";
      linkType = "HARD";
      outputName = "content-disposition-0.5.4-2d93678616";
      outputHash = "b7f4ce176e324f19324be69b05bf6f6e411160ac94bc523b782248129eb1ef3be006f6cff431aaea5e337fe5d176ce8830b8c2a1b721626ead8933f0cbe78720";
      flatName = "content-disposition";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:0.5.4";
      checksum = "10/b7f4ce176e324f19324be69b05bf6f6e411160ac94bc523b782248129eb1ef3be006f6cff431aaea5e337fe5d176ce8830b8c2a1b721626ead8933f0cbe78720";
      dependencies = {
        "safe-buffer" = packages."safe-buffer@npm:5.2.1";
      };
    };
    "content-type@npm:1.0.4" = {
      name = "content-type";
      reference = "npm:1.0.4";
      linkType = "HARD";
      outputName = "content-type-1.0.4-3b1a5ca16b";
      outputHash = "5ea85c5293475c0cdf2f84e2c71f0519ced565840fb8cbda35997cb67cc45b879d5b9dbd37760c4041ca7415a3687f8a5f2f87b556b2aaefa49c0f3436a346d4";
      flatName = "content-type";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:~1.0.4";
      checksum = "10/5ea85c5293475c0cdf2f84e2c71f0519ced565840fb8cbda35997cb67cc45b879d5b9dbd37760c4041ca7415a3687f8a5f2f87b556b2aaefa49c0f3436a346d4";
    };
    "cookie-signature@npm:1.0.6" = {
      name = "cookie-signature";
      reference = "npm:1.0.6";
      linkType = "HARD";
      outputName = "cookie-signature-1.0.6-93f325f7f0";
      outputHash = "f4e1b0a98a27a0e6e66fd7ea4e4e9d8e038f624058371bf4499cfcd8f3980be9a121486995202ba3fca74fbed93a407d6d54d43a43f96fd28d0bd7a06761591a";
      flatName = "cookie-signature";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:1.0.6";
      checksum = "10/f4e1b0a98a27a0e6e66fd7ea4e4e9d8e038f624058371bf4499cfcd8f3980be9a121486995202ba3fca74fbed93a407d6d54d43a43f96fd28d0bd7a06761591a";
    };
    "cookie@npm:0.5.0" = {
      name = "cookie";
      reference = "npm:0.5.0";
      linkType = "HARD";
      outputName = "cookie-0.5.0-e2d58a161a";
      outputHash = "aae7911ddc5f444a9025fbd979ad1b5d60191011339bce48e555cb83343d0f98b865ff5c4d71fecdfb8555a5cafdc65632f6fce172f32aaf6936830a883a0380";
      flatName = "cookie";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:0.5.0";
      checksum = "10/aae7911ddc5f444a9025fbd979ad1b5d60191011339bce48e555cb83343d0f98b865ff5c4d71fecdfb8555a5cafdc65632f6fce172f32aaf6936830a883a0380";
    };
    "debug@npm:2.6.9" = {
      name = "debug";
      reference = "npm:2.6.9";
      linkType = "HARD";
      outputName = "debug-2.6.9-7d4cb597dc";
      outputHash = "e07005f2b40e04f1bd14a3dd20520e9c4f25f60224cb006ce9d6781732c917964e9ec029fc7f1a151083cd929025ad5133814d4dc624a9aaf020effe4914ed14";
      flatName = "debug";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:2.6.9";
      checksum = "10/e07005f2b40e04f1bd14a3dd20520e9c4f25f60224cb006ce9d6781732c917964e9ec029fc7f1a151083cd929025ad5133814d4dc624a9aaf020effe4914ed14";
      dependencies = {
        "ms" = packages."ms@npm:2.0.0";
      };
      packagePeers = [
        "@types/supports-color"
        "supports-color"
      ];
    };
    "debug@virtual:759fd14db92b54abdb7afb3d21dbf8d50f1a5c59c96cd3f963ce3e3ed063bdb801142fae5f01cc81fb79f7ddc13b7c31a9deb9d5a9cfa48ec107f83de8f7f40e#npm:2.6.9" = {
      name = "debug";
      reference = "virtual:759fd14db92b54abdb7afb3d21dbf8d50f1a5c59c96cd3f963ce3e3ed063bdb801142fae5f01cc81fb79f7ddc13b7c31a9deb9d5a9cfa48ec107f83de8f7f40e#npm:2.6.9";
      canonicalPackage = packages."debug@npm:2.6.9";
      dependencies = {
        "ms" = packages."ms@npm:2.0.0";
      };
    };
    "delayed-stream@npm:1.0.0" = {
      name = "delayed-stream";
      reference = "npm:1.0.0";
      linkType = "HARD";
      outputName = "delayed-stream-1.0.0-c5a4c4cc02";
      outputHash = "46fe6e83e2cb1d85ba50bd52803c68be9bd953282fa7096f51fc29edd5d67ff84ff753c51966061e5ba7cb5e47ef6d36a91924eddb7f3f3483b1c560f77a0020";
      flatName = "delayed-stream";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:~1.0.0";
      checksum = "10/46fe6e83e2cb1d85ba50bd52803c68be9bd953282fa7096f51fc29edd5d67ff84ff753c51966061e5ba7cb5e47ef6d36a91924eddb7f3f3483b1c560f77a0020";
    };
    "depd@npm:2.0.0" = {
      name = "depd";
      reference = "npm:2.0.0";
      linkType = "HARD";
      outputName = "depd-2.0.0-b6c51a4b43";
      outputHash = "c0c8ff36079ce5ada64f46cc9d6fd47ebcf38241105b6e0c98f412e8ad91f084bcf906ff644cc3a4bd876ca27a62accb8b0fff72ea6ed1a414b89d8506f4a5ca";
      flatName = "depd";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:2.0.0";
      checksum = "10/c0c8ff36079ce5ada64f46cc9d6fd47ebcf38241105b6e0c98f412e8ad91f084bcf906ff644cc3a4bd876ca27a62accb8b0fff72ea6ed1a414b89d8506f4a5ca";
    };
    "destroy@npm:1.2.0" = {
      name = "destroy";
      reference = "npm:1.2.0";
      linkType = "HARD";
      outputName = "destroy-1.2.0-6a511802e2";
      outputHash = "0acb300b7478a08b92d810ab229d5afe0d2f4399272045ab22affa0d99dbaf12637659411530a6fcd597a9bdac718fc94373a61a95b4651bbc7b83684a565e38";
      flatName = "destroy";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:1.2.0";
      checksum = "10/0acb300b7478a08b92d810ab229d5afe0d2f4399272045ab22affa0d99dbaf12637659411530a6fcd597a9bdac718fc94373a61a95b4651bbc7b83684a565e38";
    };
    "ee-first@npm:1.1.1" = {
      name = "ee-first";
      reference = "npm:1.1.1";
      linkType = "HARD";
      outputName = "ee-first-1.1.1-33f8535b39";
      outputHash = "1b4cac778d64ce3b582a7e26b218afe07e207a0f9bfe13cc7395a6d307849cfe361e65033c3251e00c27dd060cab43014c2d6b2647676135e18b77d2d05b3f4f";
      flatName = "ee-first";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:1.1.1";
      checksum = "10/1b4cac778d64ce3b582a7e26b218afe07e207a0f9bfe13cc7395a6d307849cfe361e65033c3251e00c27dd060cab43014c2d6b2647676135e18b77d2d05b3f4f";
    };
    "encodeurl@npm:1.0.2" = {
      name = "encodeurl";
      reference = "npm:1.0.2";
      linkType = "HARD";
      outputName = "encodeurl-1.0.2-f8c8454c41";
      outputHash = "e50e3d508cdd9c4565ba72d2012e65038e5d71bdc9198cb125beb6237b5b1ade6c0d343998da9e170fb2eae52c1bed37d4d6d98a46ea423a0cddbed5ac3f780c";
      flatName = "encodeurl";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:~1.0.2";
      checksum = "10/e50e3d508cdd9c4565ba72d2012e65038e5d71bdc9198cb125beb6237b5b1ade6c0d343998da9e170fb2eae52c1bed37d4d6d98a46ea423a0cddbed5ac3f780c";
    };
    "escape-html@npm:1.0.3" = {
      name = "escape-html";
      reference = "npm:1.0.3";
      linkType = "HARD";
      outputName = "escape-html-1.0.3-376c22ee74";
      outputHash = "6213ca9ae00d0ab8bccb6d8d4e0a98e76237b2410302cf7df70aaa6591d509a2a37ce8998008cbecae8fc8ffaadf3fb0229535e6a145f3ce0b211d060decbb24";
      flatName = "escape-html";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:~1.0.3";
      checksum = "10/6213ca9ae00d0ab8bccb6d8d4e0a98e76237b2410302cf7df70aaa6591d509a2a37ce8998008cbecae8fc8ffaadf3fb0229535e6a145f3ce0b211d060decbb24";
    };
    "etag@npm:1.8.1" = {
      name = "etag";
      reference = "npm:1.8.1";
      linkType = "HARD";
      outputName = "etag-1.8.1-54a3b989d9";
      outputHash = "571aeb3dbe0f2bbd4e4fadbdb44f325fc75335cd5f6f6b6a091e6a06a9f25ed5392f0863c5442acb0646787446e816f13cbfc6edce5b07658541dff573cab1ff";
      flatName = "etag";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:~1.8.1";
      checksum = "10/571aeb3dbe0f2bbd4e4fadbdb44f325fc75335cd5f6f6b6a091e6a06a9f25ed5392f0863c5442acb0646787446e816f13cbfc6edce5b07658541dff573cab1ff";
    };
    "express-async-errors@npm:3.1.1" = {
      name = "express-async-errors";
      reference = "npm:3.1.1";
      linkType = "HARD";
      outputName = "express-async-errors-3.1.1-c0a6b1e552";
      outputHash = "dae2b88a6416daefd27a98b946a65b56492ab1d5002cb62cd9d07f03c8cd4dae098725bc590e7ad3b48d4d3be726850a5864a4c7b427660b02c43903b70463ca";
      flatName = "express-async-errors";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^3.1.1";
      checksum = "10/dae2b88a6416daefd27a98b946a65b56492ab1d5002cb62cd9d07f03c8cd4dae098725bc590e7ad3b48d4d3be726850a5864a4c7b427660b02c43903b70463ca";
      packagePeers = [
        "@types/express"
        "express"
      ];
    };
    "express-async-errors@virtual:20690b727f8f63037236fdd078fbea158240df1898ed7ac0a357d6b9ddd8d82251ae615c7402ceaf348c08556c6e72765f7c21f0bb478e101f19e0e4984d871e#npm:3.1.1" = {
      name = "express-async-errors";
      reference = "virtual:20690b727f8f63037236fdd078fbea158240df1898ed7ac0a357d6b9ddd8d82251ae615c7402ceaf348c08556c6e72765f7c21f0bb478e101f19e0e4984d871e#npm:3.1.1";
      canonicalPackage = packages."express-async-errors@npm:3.1.1";
      dependencies = {
        "express" = packages."express@npm:4.18.2";
      };
    };
    "express@npm:4.18.2" = {
      name = "express";
      reference = "npm:4.18.2";
      linkType = "HARD";
      outputName = "express-4.18.2-bb15ff679a";
      outputHash = "869ae89ed6ff4bed7b373079dc58e5dddcf2915a2669b36037ff78c99d675ae930e5fe052b35c24f56557d28a023bb1cbe3e2f2fb87eaab96a1cedd7e597809d";
      flatName = "express";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^4.17.1";
      checksum = "10/869ae89ed6ff4bed7b373079dc58e5dddcf2915a2669b36037ff78c99d675ae930e5fe052b35c24f56557d28a023bb1cbe3e2f2fb87eaab96a1cedd7e597809d";
      dependencies = {
        "accepts" = packages."accepts@npm:1.3.8";
        "array-flatten" = packages."array-flatten@npm:1.1.1";
        "body-parser" = packages."body-parser@npm:1.20.1";
        "content-disposition" = packages."content-disposition@npm:0.5.4";
        "content-type" = packages."content-type@npm:1.0.4";
        "cookie-signature" = packages."cookie-signature@npm:1.0.6";
        "cookie" = packages."cookie@npm:0.5.0";
        "depd" = packages."depd@npm:2.0.0";
        "encodeurl" = packages."encodeurl@npm:1.0.2";
        "escape-html" = packages."escape-html@npm:1.0.3";
        "etag" = packages."etag@npm:1.8.1";
        "finalhandler" = packages."finalhandler@npm:1.2.0";
        "fresh" = packages."fresh@npm:0.5.2";
        "http-errors" = packages."http-errors@npm:2.0.0";
        "merge-descriptors" = packages."merge-descriptors@npm:1.0.1";
        "methods" = packages."methods@npm:1.1.2";
        "on-finished" = packages."on-finished@npm:2.4.1";
        "parseurl" = packages."parseurl@npm:1.3.3";
        "path-to-regexp" = packages."path-to-regexp@npm:0.1.7";
        "proxy-addr" = packages."proxy-addr@npm:2.0.7";
        "qs" = packages."qs@npm:6.11.0";
        "range-parser" = packages."range-parser@npm:1.2.1";
        "safe-buffer" = packages."safe-buffer@npm:5.2.1";
        "send" = packages."send@npm:0.18.0";
        "serve-static" = packages."serve-static@npm:1.15.0";
        "setprototypeof" = packages."setprototypeof@npm:1.2.0";
        "statuses" = packages."statuses@npm:2.0.1";
        "type-is" = packages."type-is@npm:1.6.18";
        "utils-merge" = packages."utils-merge@npm:1.0.1";
        "vary" = packages."vary@npm:1.1.2";
        "debug" = packages."debug@virtual:759fd14db92b54abdb7afb3d21dbf8d50f1a5c59c96cd3f963ce3e3ed063bdb801142fae5f01cc81fb79f7ddc13b7c31a9deb9d5a9cfa48ec107f83de8f7f40e#npm:2.6.9";
      };
    };
    "finalhandler@npm:1.2.0" = {
      name = "finalhandler";
      reference = "npm:1.2.0";
      linkType = "HARD";
      outputName = "finalhandler-1.2.0-593d001463";
      outputHash = "635718cb203c6d18e6b48dfbb6c54ccb08ea470e4f474ddcef38c47edcf3227feec316f886dd701235997d8af35240cae49856721ce18f539ad038665ebbf163";
      flatName = "finalhandler";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:1.2.0";
      checksum = "10/635718cb203c6d18e6b48dfbb6c54ccb08ea470e4f474ddcef38c47edcf3227feec316f886dd701235997d8af35240cae49856721ce18f539ad038665ebbf163";
      dependencies = {
        "encodeurl" = packages."encodeurl@npm:1.0.2";
        "escape-html" = packages."escape-html@npm:1.0.3";
        "on-finished" = packages."on-finished@npm:2.4.1";
        "parseurl" = packages."parseurl@npm:1.3.3";
        "statuses" = packages."statuses@npm:2.0.1";
        "unpipe" = packages."unpipe@npm:1.0.0";
        "debug" = packages."debug@virtual:759fd14db92b54abdb7afb3d21dbf8d50f1a5c59c96cd3f963ce3e3ed063bdb801142fae5f01cc81fb79f7ddc13b7c31a9deb9d5a9cfa48ec107f83de8f7f40e#npm:2.6.9";
      };
    };
    "follow-redirects@npm:1.15.2" = {
      name = "follow-redirects";
      reference = "npm:1.15.2";
      linkType = "HARD";
      outputName = "follow-redirects-1.15.2-1ec1dd82be";
      outputHash = "8be0d39919770054812537d376850ccde0b4762b0501c440bd08724971a078123b55f57704f2984e0664fecc0c86adea85add63295804d9dce401cd9604c91d3";
      flatName = "follow-redirects";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^1.15.0";
      checksum = "10/8be0d39919770054812537d376850ccde0b4762b0501c440bd08724971a078123b55f57704f2984e0664fecc0c86adea85add63295804d9dce401cd9604c91d3";
      packagePeers = [
        "@types/debug"
        "debug"
      ];
    };
    "follow-redirects@virtual:e60543899fd705bd5f850d61bc1194b1bf7a80a922cb114420112d5561895397647171575ef119a8decf292183f1806d99bf972caa13adcdef0a1056caa42cb3#npm:1.15.2" = {
      name = "follow-redirects";
      reference = "virtual:e60543899fd705bd5f850d61bc1194b1bf7a80a922cb114420112d5561895397647171575ef119a8decf292183f1806d99bf972caa13adcdef0a1056caa42cb3#npm:1.15.2";
      canonicalPackage = packages."follow-redirects@npm:1.15.2";
    };
    "form-data@npm:4.0.0" = {
      name = "form-data";
      reference = "npm:4.0.0";
      linkType = "HARD";
      outputName = "form-data-4.0.0-916facec2d";
      outputHash = "7264aa760a8cf09482816d8300f1b6e2423de1b02bba612a136857413fdc96d7178298ced106817655facc6b89036c6e12ae31c9eb5bdc16aabf502ae8a5d805";
      flatName = "form-data";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^4.0.0";
      checksum = "10/7264aa760a8cf09482816d8300f1b6e2423de1b02bba612a136857413fdc96d7178298ced106817655facc6b89036c6e12ae31c9eb5bdc16aabf502ae8a5d805";
      dependencies = {
        "asynckit" = packages."asynckit@npm:0.4.0";
        "combined-stream" = packages."combined-stream@npm:1.0.8";
        "mime-types" = packages."mime-types@npm:2.1.35";
      };
    };
    "forwarded@npm:0.2.0" = {
      name = "forwarded";
      reference = "npm:0.2.0";
      linkType = "HARD";
      outputName = "forwarded-0.2.0-6473dabe35";
      outputHash = "29ba9fd347117144e97cbb8852baae5e8b2acb7d1b591ef85695ed96f5b933b1804a7fac4a15dd09ca7ac7d0cdc104410e8102aae2dd3faa570a797ba07adb81";
      flatName = "forwarded";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:0.2.0";
      checksum = "10/29ba9fd347117144e97cbb8852baae5e8b2acb7d1b591ef85695ed96f5b933b1804a7fac4a15dd09ca7ac7d0cdc104410e8102aae2dd3faa570a797ba07adb81";
    };
    "fresh@npm:0.5.2" = {
      name = "fresh";
      reference = "npm:0.5.2";
      linkType = "HARD";
      outputName = "fresh-0.5.2-ad2bb4c0a2";
      outputHash = "64c88e489b5d08e2f29664eb3c79c705ff9a8eb15d3e597198ef76546d4ade295897a44abb0abd2700e7ef784b2e3cbf1161e4fbf16f59129193fd1030d16da1";
      flatName = "fresh";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:0.5.2";
      checksum = "10/64c88e489b5d08e2f29664eb3c79c705ff9a8eb15d3e597198ef76546d4ade295897a44abb0abd2700e7ef784b2e3cbf1161e4fbf16f59129193fd1030d16da1";
    };
    "function-bind@npm:1.1.1" = {
      name = "function-bind";
      reference = "npm:1.1.1";
      linkType = "HARD";
      outputName = "function-bind-1.1.1-b56b322ae9";
      outputHash = "d83f2968030678f0b8c3f2183d63dcd969344eb8b55b4eb826a94ccac6de8b87c95bebffda37a6386c74f152284eb02956ff2c496897f35d32bdc2628ac68ac5";
      flatName = "function-bind";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^1.1.1";
      checksum = "10/d83f2968030678f0b8c3f2183d63dcd969344eb8b55b4eb826a94ccac6de8b87c95bebffda37a6386c74f152284eb02956ff2c496897f35d32bdc2628ac68ac5";
    };
    "get-intrinsic@npm:1.2.0" = {
      name = "get-intrinsic";
      reference = "npm:1.2.0";
      linkType = "HARD";
      outputName = "get-intrinsic-1.2.0-eb08ea9b1d";
      outputHash = "f57c5fe67a96adace4f8e80c288728bcd0ccfdc82c9cc53e4a5ef1ec857b5f7ef4b1c289e39649b1df226bace81103630bf7e128c821f82cd603450036e54f97";
      flatName = "get-intrinsic";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^1.0.2";
      checksum = "10/f57c5fe67a96adace4f8e80c288728bcd0ccfdc82c9cc53e4a5ef1ec857b5f7ef4b1c289e39649b1df226bace81103630bf7e128c821f82cd603450036e54f97";
      dependencies = {
        "function-bind" = packages."function-bind@npm:1.1.1";
        "has-symbols" = packages."has-symbols@npm:1.0.3";
        "has" = packages."has@npm:1.0.3";
      };
    };
    "has-symbols@npm:1.0.3" = {
      name = "has-symbols";
      reference = "npm:1.0.3";
      linkType = "HARD";
      outputName = "has-symbols-1.0.3-1986bff2c4";
      outputHash = "464f97a8202a7690dadd026e6d73b1ceeddd60fe6acfd06151106f050303eaa75855aaa94969df8015c11ff7c505f196114d22f7386b4a471038da5874cf5e9b";
      flatName = "has-symbols";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^1.0.3";
      checksum = "10/464f97a8202a7690dadd026e6d73b1ceeddd60fe6acfd06151106f050303eaa75855aaa94969df8015c11ff7c505f196114d22f7386b4a471038da5874cf5e9b";
    };
    "has@npm:1.0.3" = {
      name = "has";
      reference = "npm:1.0.3";
      linkType = "HARD";
      outputName = "has-1.0.3-b7f00631c1";
      outputHash = "a449f3185b1d165026e8d25f6a8c3390bd25c201ff4b8c1aaf948fc6a5fcfd6507310b8c00c13a3325795ea9791fcc3d79d61eafa313b5750438fc19183df57b";
      flatName = "has";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^1.0.3";
      checksum = "10/a449f3185b1d165026e8d25f6a8c3390bd25c201ff4b8c1aaf948fc6a5fcfd6507310b8c00c13a3325795ea9791fcc3d79d61eafa313b5750438fc19183df57b";
      dependencies = {
        "function-bind" = packages."function-bind@npm:1.1.1";
      };
    };
    "http-errors@npm:2.0.0" = {
      name = "http-errors";
      reference = "npm:2.0.0";
      linkType = "HARD";
      outputName = "http-errors-2.0.0-3f1c503428";
      outputHash = "0e7f76ee8ff8a33e58a3281a469815b893c41357378f408be8f6d4aa7d1efafb0da064625518e7078381b6a92325949b119dc38fcb30bdbc4e3a35f78c44c439";
      flatName = "http-errors";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:2.0.0";
      checksum = "10/0e7f76ee8ff8a33e58a3281a469815b893c41357378f408be8f6d4aa7d1efafb0da064625518e7078381b6a92325949b119dc38fcb30bdbc4e3a35f78c44c439";
      dependencies = {
        "depd" = packages."depd@npm:2.0.0";
        "inherits" = packages."inherits@npm:2.0.4";
        "setprototypeof" = packages."setprototypeof@npm:1.2.0";
        "statuses" = packages."statuses@npm:2.0.1";
        "toidentifier" = packages."toidentifier@npm:1.0.1";
      };
    };
    "iconv-lite@npm:0.4.24" = {
      name = "iconv-lite";
      reference = "npm:0.4.24";
      linkType = "HARD";
      outputName = "iconv-lite-0.4.24-c5c4ac6695";
      outputHash = "6d3a2dac6e5d1fb126d25645c25c3a1209f70cceecc68b8ef51ae0da3cdc078c151fade7524a30b12a3094926336831fca09c666ef55b37e2c69638b5d6bd2e3";
      flatName = "iconv-lite";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:0.4.24";
      checksum = "10/6d3a2dac6e5d1fb126d25645c25c3a1209f70cceecc68b8ef51ae0da3cdc078c151fade7524a30b12a3094926336831fca09c666ef55b37e2c69638b5d6bd2e3";
      dependencies = {
        "safer-buffer" = packages."safer-buffer@npm:2.1.2";
      };
    };
    "inherits@npm:2.0.4" = {
      name = "inherits";
      reference = "npm:2.0.4";
      linkType = "HARD";
      outputName = "inherits-2.0.4-c66b3957a0";
      outputHash = "cd45e923bee15186c07fa4c89db0aace24824c482fb887b528304694b2aa6ff8a898da8657046a5dcf3e46cd6db6c61629551f9215f208d7c3f157cf9b290521";
      flatName = "inherits";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:2.0.4";
      checksum = "10/cd45e923bee15186c07fa4c89db0aace24824c482fb887b528304694b2aa6ff8a898da8657046a5dcf3e46cd6db6c61629551f9215f208d7c3f157cf9b290521";
    };
    "ipaddr.js@npm:1.9.1" = {
      name = "ipaddr.js";
      reference = "npm:1.9.1";
      linkType = "HARD";
      outputName = "ipaddr.js-1.9.1-19ae7878b4";
      outputHash = "864d0cced0c0832700e9621913a6429ccdc67f37c1bd78fb8c6789fff35c9d167cb329134acad2290497a53336813ab4798d2794fd675d5eb33b5fdf0982b9ca";
      flatName = "ipaddr.js";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:1.9.1";
      checksum = "10/864d0cced0c0832700e9621913a6429ccdc67f37c1bd78fb8c6789fff35c9d167cb329134acad2290497a53336813ab4798d2794fd675d5eb33b5fdf0982b9ca";
    };
    "media-typer@npm:0.3.0" = {
      name = "media-typer";
      reference = "npm:0.3.0";
      linkType = "HARD";
      outputName = "media-typer-0.3.0-8674f8f0f5";
      outputHash = "38e0984db39139604756903a01397e29e17dcb04207bb3e081412ce725ab17338ecc47220c1b186b6bbe79a658aad1b0d41142884f5a481f36290cdefbe6aa46";
      flatName = "media-typer";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:0.3.0";
      checksum = "10/38e0984db39139604756903a01397e29e17dcb04207bb3e081412ce725ab17338ecc47220c1b186b6bbe79a658aad1b0d41142884f5a481f36290cdefbe6aa46";
    };
    "merge-descriptors@npm:1.0.1" = {
      name = "merge-descriptors";
      reference = "npm:1.0.1";
      linkType = "HARD";
      outputName = "merge-descriptors-1.0.1-615287aaa8";
      outputHash = "5abc259d2ae25bb06d19ce2b94a21632583c74e2a9109ee1ba7fd147aa7362b380d971e0251069f8b3eb7d48c21ac839e21fa177b335e82c76ec172e30c31a26";
      flatName = "merge-descriptors";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:1.0.1";
      checksum = "10/5abc259d2ae25bb06d19ce2b94a21632583c74e2a9109ee1ba7fd147aa7362b380d971e0251069f8b3eb7d48c21ac839e21fa177b335e82c76ec172e30c31a26";
    };
    "methods@npm:1.1.2" = {
      name = "methods";
      reference = "npm:1.1.2";
      linkType = "HARD";
      outputName = "methods-1.1.2-92f6fdb39b";
      outputHash = "a385dd974faa34b5dd021b2bbf78c722881bf6f003bfe6d391d7da3ea1ed625d1ff10ddd13c57531f628b3e785be38d3eed10ad03cebd90b76932413df9a1820";
      flatName = "methods";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:~1.1.2";
      checksum = "10/a385dd974faa34b5dd021b2bbf78c722881bf6f003bfe6d391d7da3ea1ed625d1ff10ddd13c57531f628b3e785be38d3eed10ad03cebd90b76932413df9a1820";
    };
    "mime-db@npm:1.40.0" = {
      name = "mime-db";
      reference = "npm:1.40.0";
      linkType = "HARD";
      outputName = "mime-db-1.40.0-a136b9af4b";
      outputHash = "98fc5fa6f74910d9f4b014e1d3876df69604e72c2c448e70f8c16e2e99e8394af0de21e445742d93f90d01345d83db2a689879457cf560c25ddb2f3af7b37d33";
      flatName = "mime-db";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:1.40.0";
      checksum = "10/98fc5fa6f74910d9f4b014e1d3876df69604e72c2c448e70f8c16e2e99e8394af0de21e445742d93f90d01345d83db2a689879457cf560c25ddb2f3af7b37d33";
    };
    "mime-db@npm:1.52.0" = {
      name = "mime-db";
      reference = "npm:1.52.0";
      linkType = "HARD";
      outputName = "mime-db-1.52.0-b5371d6fd2";
      outputHash = "54bb60bf39e6f8689f6622784e668a3d7f8bed6b0d886f5c3c446cb3284be28b30bf707ed05d0fe44a036f8469976b2629bbea182684977b084de9da274694d7";
      flatName = "mime-db";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:1.52.0";
      checksum = "10/54bb60bf39e6f8689f6622784e668a3d7f8bed6b0d886f5c3c446cb3284be28b30bf707ed05d0fe44a036f8469976b2629bbea182684977b084de9da274694d7";
    };
    "mime-types@npm:2.1.24" = {
      name = "mime-types";
      reference = "npm:2.1.24";
      linkType = "HARD";
      outputName = "mime-types-2.1.24-b1aaaae895";
      outputHash = "90dae1ec86b50799d4c8238e140c3ee2879bb9032d0ef6529af5e3643f5aaafd773aca5075615d199348db1132a6cf882b8e683c2c3e493259eb27ab9492ad89";
      flatName = "mime-types";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:~2.1.24";
      checksum = "10/90dae1ec86b50799d4c8238e140c3ee2879bb9032d0ef6529af5e3643f5aaafd773aca5075615d199348db1132a6cf882b8e683c2c3e493259eb27ab9492ad89";
      dependencies = {
        "mime-db" = packages."mime-db@npm:1.40.0";
      };
    };
    "mime-types@npm:2.1.35" = {
      name = "mime-types";
      reference = "npm:2.1.35";
      linkType = "HARD";
      outputName = "mime-types-2.1.35-dd9ea9f3e2";
      outputHash = "89aa9651b67644035de2784a6e665fc685d79aba61857e02b9c8758da874a754aed4a9aced9265f5ed1171fd934331e5516b84a7f0218031b6fa0270eca1e51a";
      flatName = "mime-types";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:~2.1.34";
      checksum = "10/89aa9651b67644035de2784a6e665fc685d79aba61857e02b9c8758da874a754aed4a9aced9265f5ed1171fd934331e5516b84a7f0218031b6fa0270eca1e51a";
      dependencies = {
        "mime-db" = packages."mime-db@npm:1.52.0";
      };
    };
    "mime@npm:1.6.0" = {
      name = "mime";
      reference = "npm:1.6.0";
      linkType = "HARD";
      outputName = "mime-1.6.0-60ae95038a";
      outputHash = "b7d98bb1e006c0e63e2c91b590fe1163b872abf8f7ef224d53dd31499c2197278a6d3d0864c45239b1a93d22feaf6f9477e9fc847eef945838150b8c02d03170";
      flatName = "mime";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:1.6.0";
      checksum = "10/b7d98bb1e006c0e63e2c91b590fe1163b872abf8f7ef224d53dd31499c2197278a6d3d0864c45239b1a93d22feaf6f9477e9fc847eef945838150b8c02d03170";
      bin = {
        "mime" = "cli.js";
      };
    };
    "ms@npm:2.0.0" = {
      name = "ms";
      reference = "npm:2.0.0";
      linkType = "HARD";
      outputName = "ms-2.0.0-9e1101a471";
      outputHash = "0e6a22b8b746d2e0b65a430519934fefd41b6db0682e3477c10f60c76e947c4c0ad06f63ffdf1d78d335f83edee8c0aa928aa66a36c7cd95b69b26f468d527f4";
      flatName = "ms";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:2.0.0";
      checksum = "10/0e6a22b8b746d2e0b65a430519934fefd41b6db0682e3477c10f60c76e947c4c0ad06f63ffdf1d78d335f83edee8c0aa928aa66a36c7cd95b69b26f468d527f4";
    };
    "ms@npm:2.1.3" = {
      name = "ms";
      reference = "npm:2.1.3";
      linkType = "HARD";
      outputName = "ms-2.1.3-81ff3cfac1";
      outputHash = "aa92de608021b242401676e35cfa5aa42dd70cbdc082b916da7fb925c542173e36bce97ea3e804923fe92c0ad991434e4a38327e15a1b5b5f945d66df615ae6d";
      flatName = "ms";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:2.1.3";
      checksum = "10/aa92de608021b242401676e35cfa5aa42dd70cbdc082b916da7fb925c542173e36bce97ea3e804923fe92c0ad991434e4a38327e15a1b5b5f945d66df615ae6d";
    };
    "negotiator@npm:0.6.3" = {
      name = "negotiator";
      reference = "npm:0.6.3";
      linkType = "HARD";
      outputName = "negotiator-0.6.3-9d50e36171";
      outputHash = "2723fb822a17ad55c93a588a4bc44d53b22855bf4be5499916ca0cab1e7165409d0b288ba2577d7b029f10ce18cf2ed8e703e5af31c984e1e2304277ef979837";
      flatName = "negotiator";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:0.6.3";
      checksum = "10/2723fb822a17ad55c93a588a4bc44d53b22855bf4be5499916ca0cab1e7165409d0b288ba2577d7b029f10ce18cf2ed8e703e5af31c984e1e2304277ef979837";
    };
    "object-inspect@npm:1.12.3" = {
      name = "object-inspect";
      reference = "npm:1.12.3";
      linkType = "HARD";
      outputName = "object-inspect-1.12.3-1e7d20f5ff";
      outputHash = "532b0036f0472f561180fac0d04fe328ee01f57637624c83fb054f81b5bfe966cdf4200612a499ed391a7ca3c46b20a0bc3a55fc8241d944abe687c556a32b39";
      flatName = "object-inspect";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^1.9.0";
      checksum = "10/532b0036f0472f561180fac0d04fe328ee01f57637624c83fb054f81b5bfe966cdf4200612a499ed391a7ca3c46b20a0bc3a55fc8241d944abe687c556a32b39";
    };
    "on-finished@npm:2.4.1" = {
      name = "on-finished";
      reference = "npm:2.4.1";
      linkType = "HARD";
      outputName = "on-finished-2.4.1-907af70f88";
      outputHash = "8e81472c5028125c8c39044ac4ab8ba51a7cdc19a9fbd4710f5d524a74c6d8c9ded4dd0eed83f28d3d33ac1d7a6a439ba948ccb765ac6ce87f30450a26bfe2ea";
      flatName = "on-finished";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:2.4.1";
      checksum = "10/8e81472c5028125c8c39044ac4ab8ba51a7cdc19a9fbd4710f5d524a74c6d8c9ded4dd0eed83f28d3d33ac1d7a6a439ba948ccb765ac6ce87f30450a26bfe2ea";
      dependencies = {
        "ee-first" = packages."ee-first@npm:1.1.1";
      };
    };
    "parseurl@npm:1.3.3" = {
      name = "parseurl";
      reference = "npm:1.3.3";
      linkType = "HARD";
      outputName = "parseurl-1.3.3-1542397e00";
      outputHash = "407cee8e0a3a4c5cd472559bca8b6a45b82c124e9a4703302326e9ab60fc1081442ada4e02628efef1eb16197ddc7f8822f5a91fd7d7c86b51f530aedb17dfa2";
      flatName = "parseurl";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:~1.3.3";
      checksum = "10/407cee8e0a3a4c5cd472559bca8b6a45b82c124e9a4703302326e9ab60fc1081442ada4e02628efef1eb16197ddc7f8822f5a91fd7d7c86b51f530aedb17dfa2";
    };
    "path-to-regexp@npm:0.1.7" = {
      name = "path-to-regexp";
      reference = "npm:0.1.7";
      linkType = "HARD";
      outputName = "path-to-regexp-0.1.7-2605347373";
      outputHash = "701c99e1f08e3400bea4d701cf6f03517474bb1b608da71c78b1eb261415b645c5670dfae49808c89e12cea2dccd113b069f040a80de012da0400191c6dbd1c8";
      flatName = "path-to-regexp";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:0.1.7";
      checksum = "10/701c99e1f08e3400bea4d701cf6f03517474bb1b608da71c78b1eb261415b645c5670dfae49808c89e12cea2dccd113b069f040a80de012da0400191c6dbd1c8";
    };
    "proxy-addr@npm:2.0.7" = {
      name = "proxy-addr";
      reference = "npm:2.0.7";
      linkType = "HARD";
      outputName = "proxy-addr-2.0.7-dae6552872";
      outputHash = "f24a0c80af0e75d31e3451398670d73406ec642914da11a2965b80b1898ca6f66a0e3e091a11a4327079b2b268795f6fa06691923fef91887215c3d0e8ea3f68";
      flatName = "proxy-addr";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:~2.0.7";
      checksum = "10/f24a0c80af0e75d31e3451398670d73406ec642914da11a2965b80b1898ca6f66a0e3e091a11a4327079b2b268795f6fa06691923fef91887215c3d0e8ea3f68";
      dependencies = {
        "forwarded" = packages."forwarded@npm:0.2.0";
        "ipaddr.js" = packages."ipaddr.js@npm:1.9.1";
      };
    };
    "proxy-from-env@npm:1.1.0" = {
      name = "proxy-from-env";
      reference = "npm:1.1.0";
      linkType = "HARD";
      outputName = "proxy-from-env-1.1.0-c13d07f26b";
      outputHash = "f0bb4a87cfd18f77bc2fba23ae49c3b378fb35143af16cc478171c623eebe181678f09439707ad80081d340d1593cd54a33a0113f3ccb3f4bc9451488780ee23";
      flatName = "proxy-from-env";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^1.1.0";
      checksum = "10/f0bb4a87cfd18f77bc2fba23ae49c3b378fb35143af16cc478171c623eebe181678f09439707ad80081d340d1593cd54a33a0113f3ccb3f4bc9451488780ee23";
    };
    "qs@npm:6.11.0" = {
      name = "qs";
      reference = "npm:6.11.0";
      linkType = "HARD";
      outputName = "qs-6.11.0-caf1bc9dea";
      outputHash = "5a3bfea3e2f359ede1bfa5d2f0dbe54001aa55e40e27dc3e60fab814362d83a9b30758db057c2011b6f53a2d4e4e5150194b5bac45372652aecb3e3c0d4b256e";
      flatName = "qs";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:6.11.0";
      checksum = "10/5a3bfea3e2f359ede1bfa5d2f0dbe54001aa55e40e27dc3e60fab814362d83a9b30758db057c2011b6f53a2d4e4e5150194b5bac45372652aecb3e3c0d4b256e";
      dependencies = {
        "side-channel" = packages."side-channel@npm:1.0.4";
      };
    };
    "range-parser@npm:1.2.1" = {
      name = "range-parser";
      reference = "npm:1.2.1";
      linkType = "HARD";
      outputName = "range-parser-1.2.1-1a470fa390";
      outputHash = "ce21ef2a2dd40506893157970dc76e835c78cf56437e26e19189c48d5291e7279314477b06ac38abd6a401b661a6840f7b03bd0b1249da9b691deeaa15872c26";
      flatName = "range-parser";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:~1.2.1";
      checksum = "10/ce21ef2a2dd40506893157970dc76e835c78cf56437e26e19189c48d5291e7279314477b06ac38abd6a401b661a6840f7b03bd0b1249da9b691deeaa15872c26";
    };
    "raw-body@npm:2.5.1" = {
      name = "raw-body";
      reference = "npm:2.5.1";
      linkType = "HARD";
      outputName = "raw-body-2.5.1-9dd1d9fff9";
      outputHash = "280bedc12db3490ecd06f740bdcf66093a07535374b51331242382c0e130bb273ebb611b7bc4cba1b4b4e016cc7b1f4b05a6df885a6af39c2bc3b94c02291c84";
      flatName = "raw-body";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:2.5.1";
      checksum = "10/280bedc12db3490ecd06f740bdcf66093a07535374b51331242382c0e130bb273ebb611b7bc4cba1b4b4e016cc7b1f4b05a6df885a6af39c2bc3b94c02291c84";
      dependencies = {
        "bytes" = packages."bytes@npm:3.1.2";
        "http-errors" = packages."http-errors@npm:2.0.0";
        "iconv-lite" = packages."iconv-lite@npm:0.4.24";
        "unpipe" = packages."unpipe@npm:1.0.0";
      };
    };
    "safe-buffer@npm:5.2.1" = {
      name = "safe-buffer";
      reference = "npm:5.2.1";
      linkType = "HARD";
      outputName = "safe-buffer-5.2.1-3481c8aa9b";
      outputHash = "32872cd0ff68a3ddade7a7617b8f4c2ae8764d8b7d884c651b74457967a9e0e886267d3ecc781220629c44a865167b61c375d2da6c720c840ecd73f45d5d9451";
      flatName = "safe-buffer";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:5.2.1";
      checksum = "10/32872cd0ff68a3ddade7a7617b8f4c2ae8764d8b7d884c651b74457967a9e0e886267d3ecc781220629c44a865167b61c375d2da6c720c840ecd73f45d5d9451";
    };
    "safer-buffer@npm:2.1.2" = {
      name = "safer-buffer";
      reference = "npm:2.1.2";
      linkType = "HARD";
      outputName = "safer-buffer-2.1.2-8d5c0b705e";
      outputHash = "7eaf7a0cf37cc27b42fb3ef6a9b1df6e93a1c6d98c6c6702b02fe262d5fcbd89db63320793b99b21cb5348097d0a53de81bd5f4e8b86e20cc9412e3f1cfb4e83";
      flatName = "safer-buffer";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:>= 2.1.2 < 3";
      checksum = "10/7eaf7a0cf37cc27b42fb3ef6a9b1df6e93a1c6d98c6c6702b02fe262d5fcbd89db63320793b99b21cb5348097d0a53de81bd5f4e8b86e20cc9412e3f1cfb4e83";
    };
    "send@npm:0.18.0" = {
      name = "send";
      reference = "npm:0.18.0";
      linkType = "HARD";
      outputName = "send-0.18.0-faadf6353f";
      outputHash = "ec66c0ad109680ad8141d507677cfd8b4e40b9559de23191871803ed241718e99026faa46c398dcfb9250676076573bd6bfe5d0ec347f88f4b7b8533d1d391cb";
      flatName = "send";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:0.18.0";
      checksum = "10/ec66c0ad109680ad8141d507677cfd8b4e40b9559de23191871803ed241718e99026faa46c398dcfb9250676076573bd6bfe5d0ec347f88f4b7b8533d1d391cb";
      dependencies = {
        "depd" = packages."depd@npm:2.0.0";
        "destroy" = packages."destroy@npm:1.2.0";
        "encodeurl" = packages."encodeurl@npm:1.0.2";
        "escape-html" = packages."escape-html@npm:1.0.3";
        "etag" = packages."etag@npm:1.8.1";
        "fresh" = packages."fresh@npm:0.5.2";
        "http-errors" = packages."http-errors@npm:2.0.0";
        "mime" = packages."mime@npm:1.6.0";
        "ms" = packages."ms@npm:2.1.3";
        "on-finished" = packages."on-finished@npm:2.4.1";
        "range-parser" = packages."range-parser@npm:1.2.1";
        "statuses" = packages."statuses@npm:2.0.1";
        "debug" = packages."debug@virtual:759fd14db92b54abdb7afb3d21dbf8d50f1a5c59c96cd3f963ce3e3ed063bdb801142fae5f01cc81fb79f7ddc13b7c31a9deb9d5a9cfa48ec107f83de8f7f40e#npm:2.6.9";
      };
    };
    "serve-static@npm:1.15.0" = {
      name = "serve-static";
      reference = "npm:1.15.0";
      linkType = "HARD";
      outputName = "serve-static-1.15.0-86c81879f5";
      outputHash = "699b2d4c29807a51d9b5e0f24955346911437aebb0178b3c4833ad30d3eca93385ff9927254f5c16da345903cad39d9cd4a532198c95a5129cc4ed43911b15a4";
      flatName = "serve-static";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:1.15.0";
      checksum = "10/699b2d4c29807a51d9b5e0f24955346911437aebb0178b3c4833ad30d3eca93385ff9927254f5c16da345903cad39d9cd4a532198c95a5129cc4ed43911b15a4";
      dependencies = {
        "encodeurl" = packages."encodeurl@npm:1.0.2";
        "escape-html" = packages."escape-html@npm:1.0.3";
        "parseurl" = packages."parseurl@npm:1.3.3";
        "send" = packages."send@npm:0.18.0";
      };
    };
    "setprototypeof@npm:1.2.0" = {
      name = "setprototypeof";
      reference = "npm:1.2.0";
      linkType = "HARD";
      outputName = "setprototypeof-1.2.0-0fedbdcd3a";
      outputHash = "fde1630422502fbbc19e6844346778f99d449986b2f9cdcceb8326730d2f3d9964dbcb03c02aaadaefffecd0f2c063315ebea8b3ad895914bf1afc1747fc172e";
      flatName = "setprototypeof";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:1.2.0";
      checksum = "10/fde1630422502fbbc19e6844346778f99d449986b2f9cdcceb8326730d2f3d9964dbcb03c02aaadaefffecd0f2c063315ebea8b3ad895914bf1afc1747fc172e";
    };
    "side-channel@npm:1.0.4" = {
      name = "side-channel";
      reference = "npm:1.0.4";
      linkType = "HARD";
      outputName = "side-channel-1.0.4-e1f38b9e06";
      outputHash = "c4998d9fc530b0e75a7fd791ad868fdc42846f072734f9080ff55cc8dc7d3899abcda24fd896aa6648c3ab7021b4bb478073eb4f44dfd55bce9714bc1a7c5d45";
      flatName = "side-channel";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^1.0.4";
      checksum = "10/c4998d9fc530b0e75a7fd791ad868fdc42846f072734f9080ff55cc8dc7d3899abcda24fd896aa6648c3ab7021b4bb478073eb4f44dfd55bce9714bc1a7c5d45";
      dependencies = {
        "call-bind" = packages."call-bind@npm:1.0.2";
        "get-intrinsic" = packages."get-intrinsic@npm:1.2.0";
        "object-inspect" = packages."object-inspect@npm:1.12.3";
      };
    };
    "statuses@npm:2.0.1" = {
      name = "statuses";
      reference = "npm:2.0.1";
      linkType = "HARD";
      outputName = "statuses-2.0.1-81d2b97fee";
      outputHash = "18c7623fdb8f646fb213ca4051be4df7efb3484d4ab662937ca6fbef7ced9b9e12842709872eb3020cc3504b93bde88935c9f6417489627a7786f24f8031cbcb";
      flatName = "statuses";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:2.0.1";
      checksum = "10/18c7623fdb8f646fb213ca4051be4df7efb3484d4ab662937ca6fbef7ced9b9e12842709872eb3020cc3504b93bde88935c9f6417489627a7786f24f8031cbcb";
    };
    "terraform-vault-http-backend@workspace:." = {
      name = "terraform-vault-http-backend";
      reference = "workspace:.";
      linkType = "SOFT";
      outputName = "terraform-vault-http-backend-1.0.0-20690b727f";
      src = ./.;
      shouldBeUnplugged = true;
      flatName = "terraform-vault-http-backend";
      languageName = "unknown";
      scope = null;
      descriptorRange = "workspace:.";
      bin = {
        "terraform-vault-http-backend" = "index.js";
      };
      dependencies = {
        "axios" = packages."axios@npm:1.3.2";
        "body-parser" = packages."body-parser@npm:1.20.1";
        "express" = packages."express@npm:4.18.2";
        "express-async-errors" = packages."express-async-errors@virtual:20690b727f8f63037236fdd078fbea158240df1898ed7ac0a357d6b9ddd8d82251ae615c7402ceaf348c08556c6e72765f7c21f0bb478e101f19e0e4984d871e#npm:3.1.1";
      };
    };
    "toidentifier@npm:1.0.1" = {
      name = "toidentifier";
      reference = "npm:1.0.1";
      linkType = "HARD";
      outputName = "toidentifier-1.0.1-f759712599";
      outputHash = "952c29e2a85d7123239b5cfdd889a0dde47ab0497f0913d70588f19c53f7e0b5327c95f4651e413c74b785147f9637b17410ac8c846d5d4a20a5a33eb6dc3a45";
      flatName = "toidentifier";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:1.0.1";
      checksum = "10/952c29e2a85d7123239b5cfdd889a0dde47ab0497f0913d70588f19c53f7e0b5327c95f4651e413c74b785147f9637b17410ac8c846d5d4a20a5a33eb6dc3a45";
    };
    "type-is@npm:1.6.18" = {
      name = "type-is";
      reference = "npm:1.6.18";
      linkType = "HARD";
      outputName = "type-is-1.6.18-6dee4d4961";
      outputHash = "0bd9eeae5efd27d98fd63519f999908c009e148039d8e7179a074f105362d4fcc214c38b24f6cda79c87e563cbd12083a4691381ed28559220d4a10c2047bed4";
      flatName = "type-is";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:~1.6.18";
      checksum = "10/0bd9eeae5efd27d98fd63519f999908c009e148039d8e7179a074f105362d4fcc214c38b24f6cda79c87e563cbd12083a4691381ed28559220d4a10c2047bed4";
      dependencies = {
        "media-typer" = packages."media-typer@npm:0.3.0";
        "mime-types" = packages."mime-types@npm:2.1.24";
      };
    };
    "unpipe@npm:1.0.0" = {
      name = "unpipe";
      reference = "npm:1.0.0";
      linkType = "HARD";
      outputName = "unpipe-1.0.0-2ed2a3c2bf";
      outputHash = "4fa18d8d8d977c55cb09715385c203197105e10a6d220087ec819f50cb68870f02942244f1017565484237f1f8c5d3cd413631b1ae104d3096f24fdfde1b4aa2";
      flatName = "unpipe";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:~1.0.0";
      checksum = "10/4fa18d8d8d977c55cb09715385c203197105e10a6d220087ec819f50cb68870f02942244f1017565484237f1f8c5d3cd413631b1ae104d3096f24fdfde1b4aa2";
    };
    "utils-merge@npm:1.0.1" = {
      name = "utils-merge";
      reference = "npm:1.0.1";
      linkType = "HARD";
      outputName = "utils-merge-1.0.1-363bbdfbca";
      outputHash = "5d6949693d58cb2e636a84f3ee1c6e7b2f9c16cb1d42d0ecb386d8c025c69e327205aa1c69e2868cc06a01e5e20681fbba55a4e0ed0cce913d60334024eae798";
      flatName = "utils-merge";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:1.0.1";
      checksum = "10/5d6949693d58cb2e636a84f3ee1c6e7b2f9c16cb1d42d0ecb386d8c025c69e327205aa1c69e2868cc06a01e5e20681fbba55a4e0ed0cce913d60334024eae798";
    };
    "vary@npm:1.1.2" = {
      name = "vary";
      reference = "npm:1.1.2";
      linkType = "HARD";
      outputName = "vary-1.1.2-b49f70ae63";
      outputHash = "31389debef15a480849b8331b220782230b9815a8e0dbb7b9a8369559aed2e9a7800cd904d4371ea74f4c3527db456dc8e7ac5befce5f0d289014dbdf47b2242";
      flatName = "vary";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:~1.1.2";
      checksum = "10/31389debef15a480849b8331b220782230b9815a8e0dbb7b9a8369559aed2e9a7800cd904d4371ea74f4c3527db456dc8e7ac5befce5f0d289014dbdf47b2242";
    };
  };
in
{ inherit packages; inherit settings; }
