# This file is generated by running "yarn install" inside your project.
# It is essentially a version of yarn.lock that Nix can better understand
# Manual changes WILL be lost - proceed with caution!
let
  packages = {
    "accepts@npm:1.3.8" = {
      name = "accepts";
      reference = "npm:1.3.8";
      linkType = "HARD";
      outputName = "accepts-1.3.8-9a812371c9";
      outputHash = "4634cf08b9ccf6a7618a006d54b6a29c159c233eb40194e397373308244ebad0436155d0604463d401673d47c1e1f65ea1237d58cbe8ad780d01f20f61ce19f4";
      flatName = "accepts";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:~1.3.8";
      checksum = "9/4634cf08b9ccf6a7618a006d54b6a29c159c233eb40194e397373308244ebad0436155d0604463d401673d47c1e1f65ea1237d58cbe8ad780d01f20f61ce19f4";
      dependencies = {
        "mime-types" = packages."mime-types@npm:2.1.35";
        "negotiator" = packages."negotiator@npm:0.6.3";
      };
    };
    "array-flatten@npm:1.1.1" = {
      name = "array-flatten";
      reference = "npm:1.1.1";
      linkType = "HARD";
      outputName = "array-flatten-1.1.1-9d94ad5f1d";
      outputHash = "4f31d5671990976098f6ea9d82986748f43d0d44e3ab815d84d33cd5369ee964386804213619d4d050b33fe1cefa5e1420e98d350cd0162ab087d9d58c02d1c4";
      flatName = "array-flatten";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:1.1.1";
      checksum = "9/4f31d5671990976098f6ea9d82986748f43d0d44e3ab815d84d33cd5369ee964386804213619d4d050b33fe1cefa5e1420e98d350cd0162ab087d9d58c02d1c4";
    };
    "asynckit@npm:0.4.0" = {
      name = "asynckit";
      reference = "npm:0.4.0";
      linkType = "HARD";
      outputName = "asynckit-0.4.0-c718858525";
      outputHash = "e4d1381289f9effe69a4dbc18e8b4e2059113dfb23634d0f4064226042870dbc53175fbf261f982d055fa2952163a8b7608781ea58314a17bb6a2cd6815af4f1";
      flatName = "asynckit";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^0.4.0";
      checksum = "9/e4d1381289f9effe69a4dbc18e8b4e2059113dfb23634d0f4064226042870dbc53175fbf261f982d055fa2952163a8b7608781ea58314a17bb6a2cd6815af4f1";
    };
    "axios@npm:1.3.2" = {
      name = "axios";
      reference = "npm:1.3.2";
      linkType = "HARD";
      outputName = "axios-1.3.2-e60543899f";
      outputHash = "d70325ae823919b0d1c5b3a41392780f12dfafa666cf688c1948e72fc5ad4fe6ffdd7bfc1aa63fcbda54bba500dfadf680ad675632af72de18269626e9e18b67";
      flatName = "axios";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^1.3.2";
      checksum = "9/d70325ae823919b0d1c5b3a41392780f12dfafa666cf688c1948e72fc5ad4fe6ffdd7bfc1aa63fcbda54bba500dfadf680ad675632af72de18269626e9e18b67";
      dependencies = {
        "form-data" = packages."form-data@npm:4.0.0";
        "proxy-from-env" = packages."proxy-from-env@npm:1.1.0";
        "follow-redirects" = packages."follow-redirects@virtual:e60543899fd705bd5f850d61bc1194b1bf7a80a922cb114420112d5561895397647171575ef119a8decf292183f1806d99bf972caa13adcdef0a1056caa42cb3#npm:1.15.2";
      };
    };
    "body-parser@npm:1.20.1" = {
      name = "body-parser";
      reference = "npm:1.20.1";
      linkType = "HARD";
      outputName = "body-parser-1.20.1-759fd14db9";
      outputHash = "33f202c9d5e21f9364ecbcc6704b637104e3a802c81e3cc0b05af94681ce3984e2792bb8d05fe5e3471ac0179c13c8d9da80034178a513ebf4b4ab0d56823617";
      flatName = "body-parser";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^1.19.0";
      checksum = "9/33f202c9d5e21f9364ecbcc6704b637104e3a802c81e3cc0b05af94681ce3984e2792bb8d05fe5e3471ac0179c13c8d9da80034178a513ebf4b4ab0d56823617";
      dependencies = {
        "bytes" = packages."bytes@npm:3.1.2";
        "content-type" = packages."content-type@npm:1.0.4";
        "depd" = packages."depd@npm:2.0.0";
        "destroy" = packages."destroy@npm:1.2.0";
        "http-errors" = packages."http-errors@npm:2.0.0";
        "iconv-lite" = packages."iconv-lite@npm:0.4.24";
        "on-finished" = packages."on-finished@npm:2.4.1";
        "qs" = packages."qs@npm:6.11.0";
        "raw-body" = packages."raw-body@npm:2.5.1";
        "type-is" = packages."type-is@npm:1.6.18";
        "unpipe" = packages."unpipe@npm:1.0.0";
        "debug" = packages."debug@virtual:759fd14db92b54abdb7afb3d21dbf8d50f1a5c59c96cd3f963ce3e3ed063bdb801142fae5f01cc81fb79f7ddc13b7c31a9deb9d5a9cfa48ec107f83de8f7f40e#npm:2.6.9";
      };
    };
    "bytes@npm:3.1.2" = {
      name = "bytes";
      reference = "npm:3.1.2";
      linkType = "HARD";
      outputName = "bytes-3.1.2-28b8643004";
      outputHash = "b9b056ed671c71c7e0f4ce7b60a0c17305d1e3e9b6c967e0e82ce85bd8fad16efa4df992177d429e253b47c45a716e6823a9d046b660b4b5b7e1e21b4801edfe";
      flatName = "bytes";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:3.1.2";
      checksum = "9/b9b056ed671c71c7e0f4ce7b60a0c17305d1e3e9b6c967e0e82ce85bd8fad16efa4df992177d429e253b47c45a716e6823a9d046b660b4b5b7e1e21b4801edfe";
    };
    "call-bind@npm:1.0.2" = {
      name = "call-bind";
      reference = "npm:1.0.2";
      linkType = "HARD";
      outputName = "call-bind-1.0.2-c957124861";
      outputHash = "6fccea8a00310bf2e2b2a07aca0eddbdcd5de2eec9dfe880c1c8b0b7fd3c6809bf28aab0209aa530a35a2fba48587733521df7f83f8d5354047afed78b69a36b";
      flatName = "call-bind";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^1.0.0";
      checksum = "9/6fccea8a00310bf2e2b2a07aca0eddbdcd5de2eec9dfe880c1c8b0b7fd3c6809bf28aab0209aa530a35a2fba48587733521df7f83f8d5354047afed78b69a36b";
      dependencies = {
        "function-bind" = packages."function-bind@npm:1.1.1";
        "get-intrinsic" = packages."get-intrinsic@npm:1.2.0";
      };
    };
    "combined-stream@npm:1.0.8" = {
      name = "combined-stream";
      reference = "npm:1.0.8";
      linkType = "HARD";
      outputName = "combined-stream-1.0.8-dc14d4a63a";
      outputHash = "c3224efc798a4f2066ff2f65c28d60b48ec73b38bf76331ecc61814875cc5c8a93beccc268ca08aaa98a141c262de5787d68685b6682b8b67ad2dadb8bd2ddd2";
      flatName = "combined-stream";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^1.0.8";
      checksum = "9/c3224efc798a4f2066ff2f65c28d60b48ec73b38bf76331ecc61814875cc5c8a93beccc268ca08aaa98a141c262de5787d68685b6682b8b67ad2dadb8bd2ddd2";
      dependencies = {
        "delayed-stream" = packages."delayed-stream@npm:1.0.0";
      };
    };
    "content-disposition@npm:0.5.4" = {
      name = "content-disposition";
      reference = "npm:0.5.4";
      linkType = "HARD";
      outputName = "content-disposition-0.5.4-2d93678616";
      outputHash = "d38295838d0d136bf434c58deb24b574d66486234832bc97be293d0bd2350acb95a548def1071817346facde253f352f48e7d4ee187f08995b9a6c8317361a5c";
      flatName = "content-disposition";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:0.5.4";
      checksum = "9/d38295838d0d136bf434c58deb24b574d66486234832bc97be293d0bd2350acb95a548def1071817346facde253f352f48e7d4ee187f08995b9a6c8317361a5c";
      dependencies = {
        "safe-buffer" = packages."safe-buffer@npm:5.2.1";
      };
    };
    "content-type@npm:1.0.4" = {
      name = "content-type";
      reference = "npm:1.0.4";
      linkType = "HARD";
      outputName = "content-type-1.0.4-3b1a5ca16b";
      outputHash = "20bda9bccfb0086d4e4b35cc5c6073b693d4a8ff0a0da0b68cf283c34a649a5d07068fd240c1ed503a7696dbbf4c875cecb708ea219db1880fbfa40e8fb02620";
      flatName = "content-type";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:~1.0.4";
      checksum = "9/20bda9bccfb0086d4e4b35cc5c6073b693d4a8ff0a0da0b68cf283c34a649a5d07068fd240c1ed503a7696dbbf4c875cecb708ea219db1880fbfa40e8fb02620";
    };
    "cookie-signature@npm:1.0.6" = {
      name = "cookie-signature";
      reference = "npm:1.0.6";
      linkType = "HARD";
      outputName = "cookie-signature-1.0.6-93f325f7f0";
      outputHash = "b99cb14f01bd69029eba0a24f3468034a590ff9ca048dcd37dcb344be2edf8691de8bbef8acffbadc2c5b38f6064fd7eb79714054458f6b714af3e25a884a9f5";
      flatName = "cookie-signature";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:1.0.6";
      checksum = "9/b99cb14f01bd69029eba0a24f3468034a590ff9ca048dcd37dcb344be2edf8691de8bbef8acffbadc2c5b38f6064fd7eb79714054458f6b714af3e25a884a9f5";
    };
    "cookie@npm:0.5.0" = {
      name = "cookie";
      reference = "npm:0.5.0";
      linkType = "HARD";
      outputName = "cookie-0.5.0-e2d58a161a";
      outputHash = "23bd6dd64f025869373c6f3c72a870b9bd0e0e6a0ffe734229c032d7aca51972ba584b39100c09141b18043e790862425aae4a60d7449fca565b21cdae0cb3c3";
      flatName = "cookie";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:0.5.0";
      checksum = "9/23bd6dd64f025869373c6f3c72a870b9bd0e0e6a0ffe734229c032d7aca51972ba584b39100c09141b18043e790862425aae4a60d7449fca565b21cdae0cb3c3";
    };
    "debug@npm:2.6.9" = {
      name = "debug";
      reference = "npm:2.6.9";
      linkType = "HARD";
      outputName = "debug-2.6.9-7d4cb597dc";
      outputHash = "143f776060e764362b11d8788c6ef7b125fe930f0b5766559c11521af6dfc256979726167a66218249d8e2f99548c1a8bdb026aad577deecc86b56b4652d4626";
      flatName = "debug";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:2.6.9";
      checksum = "9/143f776060e764362b11d8788c6ef7b125fe930f0b5766559c11521af6dfc256979726167a66218249d8e2f99548c1a8bdb026aad577deecc86b56b4652d4626";
      dependencies = {
        "ms" = packages."ms@npm:2.0.0";
      };
      packagePeers = [
        "@types/supports-color"
        "supports-color"
      ];
    };
    "debug@virtual:759fd14db92b54abdb7afb3d21dbf8d50f1a5c59c96cd3f963ce3e3ed063bdb801142fae5f01cc81fb79f7ddc13b7c31a9deb9d5a9cfa48ec107f83de8f7f40e#npm:2.6.9" = {
      name = "debug";
      reference = "virtual:759fd14db92b54abdb7afb3d21dbf8d50f1a5c59c96cd3f963ce3e3ed063bdb801142fae5f01cc81fb79f7ddc13b7c31a9deb9d5a9cfa48ec107f83de8f7f40e#npm:2.6.9";
      canonicalPackage = packages."debug@npm:2.6.9";
      dependencies = {
        "ms" = packages."ms@npm:2.0.0";
      };
    };
    "delayed-stream@npm:1.0.0" = {
      name = "delayed-stream";
      reference = "npm:1.0.0";
      linkType = "HARD";
      outputName = "delayed-stream-1.0.0-c5a4c4cc02";
      outputHash = "22f11ed342773dbc427e84d5a972e5c67fc34a44bf80eead5a41d8697c9303ae32991e568921cbd82553deeb1b33f3d6ecc148bf0efe3789589c8cb7b0e1a53a";
      flatName = "delayed-stream";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:~1.0.0";
      checksum = "9/22f11ed342773dbc427e84d5a972e5c67fc34a44bf80eead5a41d8697c9303ae32991e568921cbd82553deeb1b33f3d6ecc148bf0efe3789589c8cb7b0e1a53a";
    };
    "depd@npm:2.0.0" = {
      name = "depd";
      reference = "npm:2.0.0";
      linkType = "HARD";
      outputName = "depd-2.0.0-b6c51a4b43";
      outputHash = "170e90bfa90081462303140623fdf938aeba2f066b1c7a9a1c599b257ea8127d36b9d39fad5a9d71f5282a3bb5a8ca287ce4d8c6cecd0f65e6bf3779cc6091be";
      flatName = "depd";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:2.0.0";
      checksum = "9/170e90bfa90081462303140623fdf938aeba2f066b1c7a9a1c599b257ea8127d36b9d39fad5a9d71f5282a3bb5a8ca287ce4d8c6cecd0f65e6bf3779cc6091be";
    };
    "destroy@npm:1.2.0" = {
      name = "destroy";
      reference = "npm:1.2.0";
      linkType = "HARD";
      outputName = "destroy-1.2.0-6a511802e2";
      outputHash = "dc7c93cc92fefb26b1fd5251603da79b0289d06b6891743cb16ac11564aaf0cc985e89efb663322a39a477c4c7f2da51321bf82bb513280a12171cef63b60a21";
      flatName = "destroy";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:1.2.0";
      checksum = "9/dc7c93cc92fefb26b1fd5251603da79b0289d06b6891743cb16ac11564aaf0cc985e89efb663322a39a477c4c7f2da51321bf82bb513280a12171cef63b60a21";
    };
    "ee-first@npm:1.1.1" = {
      name = "ee-first";
      reference = "npm:1.1.1";
      linkType = "HARD";
      outputName = "ee-first-1.1.1-33f8535b39";
      outputHash = "037800fb1ddc8398702b8fdac0507da850804a43bcc623ccb7969a2ebecb384f1d0dec43dc74dc8b11eeb7652ba8fe5cba9ccce26ee6c78454b38439a5051560";
      flatName = "ee-first";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:1.1.1";
      checksum = "9/037800fb1ddc8398702b8fdac0507da850804a43bcc623ccb7969a2ebecb384f1d0dec43dc74dc8b11eeb7652ba8fe5cba9ccce26ee6c78454b38439a5051560";
    };
    "encodeurl@npm:1.0.2" = {
      name = "encodeurl";
      reference = "npm:1.0.2";
      linkType = "HARD";
      outputName = "encodeurl-1.0.2-f8c8454c41";
      outputHash = "3c87693cb4bf8e6e0da8b549c30c12f638e55c51195048de49c412b3b6c63feced7cbf4743d69e41fc4373cc39bbc6519968faad0e3c8ea24a5c125b727aa79d";
      flatName = "encodeurl";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:~1.0.2";
      checksum = "9/3c87693cb4bf8e6e0da8b549c30c12f638e55c51195048de49c412b3b6c63feced7cbf4743d69e41fc4373cc39bbc6519968faad0e3c8ea24a5c125b727aa79d";
    };
    "escape-html@npm:1.0.3" = {
      name = "escape-html";
      reference = "npm:1.0.3";
      linkType = "HARD";
      outputName = "escape-html-1.0.3-376c22ee74";
      outputHash = "c2c0e204bdee0452b5481e18e659d8f0ef909b774cd8140724e53df3254e75c04e8ff30298f658ca0310191f46de5bbb94459fc55103eb978eb6ffaaf499bbd1";
      flatName = "escape-html";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:~1.0.3";
      checksum = "9/c2c0e204bdee0452b5481e18e659d8f0ef909b774cd8140724e53df3254e75c04e8ff30298f658ca0310191f46de5bbb94459fc55103eb978eb6ffaaf499bbd1";
    };
    "etag@npm:1.8.1" = {
      name = "etag";
      reference = "npm:1.8.1";
      linkType = "HARD";
      outputName = "etag-1.8.1-54a3b989d9";
      outputHash = "70d88dfb36416dffbb09859cb5c72a71ae9a0b3da550643a75d28d3a853c999fb30076bc33d2a1c3882988e3631093b148bacaee133e070de4798e63753b82ac";
      flatName = "etag";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:~1.8.1";
      checksum = "9/70d88dfb36416dffbb09859cb5c72a71ae9a0b3da550643a75d28d3a853c999fb30076bc33d2a1c3882988e3631093b148bacaee133e070de4798e63753b82ac";
    };
    "express-async-errors@npm:3.1.1" = {
      name = "express-async-errors";
      reference = "npm:3.1.1";
      linkType = "HARD";
      outputName = "express-async-errors-3.1.1-c0a6b1e552";
      outputHash = "cea5751910ca825ceb8bdc23638b99864d41c9b0da3965381c59cb5d88fd2e90a5264fcc95d9abbc1a08848ad2dddaa448ad4b582ab4dc4c0e125f383db38687";
      flatName = "express-async-errors";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^3.1.1";
      checksum = "9/cea5751910ca825ceb8bdc23638b99864d41c9b0da3965381c59cb5d88fd2e90a5264fcc95d9abbc1a08848ad2dddaa448ad4b582ab4dc4c0e125f383db38687";
      packagePeers = [
        "@types/express"
        "express"
      ];
    };
    "express-async-errors@virtual:20690b727f8f63037236fdd078fbea158240df1898ed7ac0a357d6b9ddd8d82251ae615c7402ceaf348c08556c6e72765f7c21f0bb478e101f19e0e4984d871e#npm:3.1.1" = {
      name = "express-async-errors";
      reference = "virtual:20690b727f8f63037236fdd078fbea158240df1898ed7ac0a357d6b9ddd8d82251ae615c7402ceaf348c08556c6e72765f7c21f0bb478e101f19e0e4984d871e#npm:3.1.1";
      canonicalPackage = packages."express-async-errors@npm:3.1.1";
      dependencies = {
        "express" = packages."express@npm:4.18.2";
      };
    };
    "express@npm:4.18.2" = {
      name = "express";
      reference = "npm:4.18.2";
      linkType = "HARD";
      outputName = "express-4.18.2-bb15ff679a";
      outputHash = "997d5407a0865f35ef7218c68ad23e846a1139d2cfc524ba9f58b7f3a54d9735edc0d992d896aaee62753ccd97be83d77a507511916972f0dfcd8f938216bc3e";
      flatName = "express";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^4.17.1";
      checksum = "9/997d5407a0865f35ef7218c68ad23e846a1139d2cfc524ba9f58b7f3a54d9735edc0d992d896aaee62753ccd97be83d77a507511916972f0dfcd8f938216bc3e";
      dependencies = {
        "accepts" = packages."accepts@npm:1.3.8";
        "array-flatten" = packages."array-flatten@npm:1.1.1";
        "body-parser" = packages."body-parser@npm:1.20.1";
        "content-disposition" = packages."content-disposition@npm:0.5.4";
        "content-type" = packages."content-type@npm:1.0.4";
        "cookie-signature" = packages."cookie-signature@npm:1.0.6";
        "cookie" = packages."cookie@npm:0.5.0";
        "depd" = packages."depd@npm:2.0.0";
        "encodeurl" = packages."encodeurl@npm:1.0.2";
        "escape-html" = packages."escape-html@npm:1.0.3";
        "etag" = packages."etag@npm:1.8.1";
        "finalhandler" = packages."finalhandler@npm:1.2.0";
        "fresh" = packages."fresh@npm:0.5.2";
        "http-errors" = packages."http-errors@npm:2.0.0";
        "merge-descriptors" = packages."merge-descriptors@npm:1.0.1";
        "methods" = packages."methods@npm:1.1.2";
        "on-finished" = packages."on-finished@npm:2.4.1";
        "parseurl" = packages."parseurl@npm:1.3.3";
        "path-to-regexp" = packages."path-to-regexp@npm:0.1.7";
        "proxy-addr" = packages."proxy-addr@npm:2.0.7";
        "qs" = packages."qs@npm:6.11.0";
        "range-parser" = packages."range-parser@npm:1.2.1";
        "safe-buffer" = packages."safe-buffer@npm:5.2.1";
        "send" = packages."send@npm:0.18.0";
        "serve-static" = packages."serve-static@npm:1.15.0";
        "setprototypeof" = packages."setprototypeof@npm:1.2.0";
        "statuses" = packages."statuses@npm:2.0.1";
        "type-is" = packages."type-is@npm:1.6.18";
        "utils-merge" = packages."utils-merge@npm:1.0.1";
        "vary" = packages."vary@npm:1.1.2";
        "debug" = packages."debug@virtual:759fd14db92b54abdb7afb3d21dbf8d50f1a5c59c96cd3f963ce3e3ed063bdb801142fae5f01cc81fb79f7ddc13b7c31a9deb9d5a9cfa48ec107f83de8f7f40e#npm:2.6.9";
      };
    };
    "finalhandler@npm:1.2.0" = {
      name = "finalhandler";
      reference = "npm:1.2.0";
      linkType = "HARD";
      outputName = "finalhandler-1.2.0-593d001463";
      outputHash = "31ca595367c936c6614f67bd94c7e64a31ad9b8bd52751811b4f9deb666928d8da578a230baacf7760845126ef35330382a2e935f0757d22312ba942056dc1c1";
      flatName = "finalhandler";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:1.2.0";
      checksum = "9/31ca595367c936c6614f67bd94c7e64a31ad9b8bd52751811b4f9deb666928d8da578a230baacf7760845126ef35330382a2e935f0757d22312ba942056dc1c1";
      dependencies = {
        "encodeurl" = packages."encodeurl@npm:1.0.2";
        "escape-html" = packages."escape-html@npm:1.0.3";
        "on-finished" = packages."on-finished@npm:2.4.1";
        "parseurl" = packages."parseurl@npm:1.3.3";
        "statuses" = packages."statuses@npm:2.0.1";
        "unpipe" = packages."unpipe@npm:1.0.0";
        "debug" = packages."debug@virtual:759fd14db92b54abdb7afb3d21dbf8d50f1a5c59c96cd3f963ce3e3ed063bdb801142fae5f01cc81fb79f7ddc13b7c31a9deb9d5a9cfa48ec107f83de8f7f40e#npm:2.6.9";
      };
    };
    "follow-redirects@npm:1.15.2" = {
      name = "follow-redirects";
      reference = "npm:1.15.2";
      linkType = "HARD";
      outputName = "follow-redirects-1.15.2-1ec1dd82be";
      outputHash = "930171f8b81bf00e9368df4b17f3b835934762d51192632af53a51a8a608d5510a1ffbc6da5761dce9996cdbd750740490ca844320e5ff11cdaf2329a5a69647";
      flatName = "follow-redirects";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^1.15.0";
      checksum = "9/930171f8b81bf00e9368df4b17f3b835934762d51192632af53a51a8a608d5510a1ffbc6da5761dce9996cdbd750740490ca844320e5ff11cdaf2329a5a69647";
      packagePeers = [
        "@types/debug"
        "debug"
      ];
    };
    "follow-redirects@virtual:e60543899fd705bd5f850d61bc1194b1bf7a80a922cb114420112d5561895397647171575ef119a8decf292183f1806d99bf972caa13adcdef0a1056caa42cb3#npm:1.15.2" = {
      name = "follow-redirects";
      reference = "virtual:e60543899fd705bd5f850d61bc1194b1bf7a80a922cb114420112d5561895397647171575ef119a8decf292183f1806d99bf972caa13adcdef0a1056caa42cb3#npm:1.15.2";
      canonicalPackage = packages."follow-redirects@npm:1.15.2";
    };
    "form-data@npm:4.0.0" = {
      name = "form-data";
      reference = "npm:4.0.0";
      linkType = "HARD";
      outputName = "form-data-4.0.0-916facec2d";
      outputHash = "de37c5684d843842d2cc2bc44a975d9fecdf1df30d061c90b62fc0caeeeeb45794bceaba7aa52ee5eae8ede01ba44215b26c58f41cf64271c513787b7241fce4";
      flatName = "form-data";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^4.0.0";
      checksum = "9/de37c5684d843842d2cc2bc44a975d9fecdf1df30d061c90b62fc0caeeeeb45794bceaba7aa52ee5eae8ede01ba44215b26c58f41cf64271c513787b7241fce4";
      dependencies = {
        "asynckit" = packages."asynckit@npm:0.4.0";
        "combined-stream" = packages."combined-stream@npm:1.0.8";
        "mime-types" = packages."mime-types@npm:2.1.35";
      };
    };
    "forwarded@npm:0.2.0" = {
      name = "forwarded";
      reference = "npm:0.2.0";
      linkType = "HARD";
      outputName = "forwarded-0.2.0-6473dabe35";
      outputHash = "d1d18e065b310fb44e3190497119b810db59da95a8ac0ba186e94385484c72e189e9a5da404a209886fdcfaacc1efcb066e7d90c4281dfd7e3ce3ccd18a8dd32";
      flatName = "forwarded";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:0.2.0";
      checksum = "9/d1d18e065b310fb44e3190497119b810db59da95a8ac0ba186e94385484c72e189e9a5da404a209886fdcfaacc1efcb066e7d90c4281dfd7e3ce3ccd18a8dd32";
    };
    "fresh@npm:0.5.2" = {
      name = "fresh";
      reference = "npm:0.5.2";
      linkType = "HARD";
      outputName = "fresh-0.5.2-ad2bb4c0a2";
      outputHash = "57c25f8cdc1c8db81fc3477b8073627614c5132ae7070c8e920ff35afbddb32f98d74ab6828d92f1e1c52583b2f8ea16ac7991406ffe2bb4ec752b1aaa94350e";
      flatName = "fresh";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:0.5.2";
      checksum = "9/57c25f8cdc1c8db81fc3477b8073627614c5132ae7070c8e920ff35afbddb32f98d74ab6828d92f1e1c52583b2f8ea16ac7991406ffe2bb4ec752b1aaa94350e";
    };
    "function-bind@npm:1.1.1" = {
      name = "function-bind";
      reference = "npm:1.1.1";
      linkType = "HARD";
      outputName = "function-bind-1.1.1-b56b322ae9";
      outputHash = "8a644b8118679030cb3aeb783b024a9ee358b15c5780bdb49fe5d482f6df54672bda860e19bce87d756a5e165740caaa96f5e8487fa98933c327f631e23a5490";
      flatName = "function-bind";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^1.1.1";
      checksum = "9/8a644b8118679030cb3aeb783b024a9ee358b15c5780bdb49fe5d482f6df54672bda860e19bce87d756a5e165740caaa96f5e8487fa98933c327f631e23a5490";
    };
    "get-intrinsic@npm:1.2.0" = {
      name = "get-intrinsic";
      reference = "npm:1.2.0";
      linkType = "HARD";
      outputName = "get-intrinsic-1.2.0-eb08ea9b1d";
      outputHash = "6db1e521478d0a0f4e61c94c23e7a731b163d2904067b1b6efcac78e8b015404883dab4acb5570517df55aab6eb23eeef6a8d7310de76d9570fcbce4a3f80b18";
      flatName = "get-intrinsic";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^1.0.2";
      checksum = "9/6db1e521478d0a0f4e61c94c23e7a731b163d2904067b1b6efcac78e8b015404883dab4acb5570517df55aab6eb23eeef6a8d7310de76d9570fcbce4a3f80b18";
      dependencies = {
        "function-bind" = packages."function-bind@npm:1.1.1";
        "has-symbols" = packages."has-symbols@npm:1.0.3";
        "has" = packages."has@npm:1.0.3";
      };
    };
    "has-symbols@npm:1.0.3" = {
      name = "has-symbols";
      reference = "npm:1.0.3";
      linkType = "HARD";
      outputName = "has-symbols-1.0.3-1986bff2c4";
      outputHash = "2d0abb3382da2945b1b8d9a4afebc8a0770fe07198e727b4fbd7f616c70796f040bf2bd8d6db47e0c590507812a2680594fc77f871238289f6c7870318cf62c9";
      flatName = "has-symbols";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^1.0.3";
      checksum = "9/2d0abb3382da2945b1b8d9a4afebc8a0770fe07198e727b4fbd7f616c70796f040bf2bd8d6db47e0c590507812a2680594fc77f871238289f6c7870318cf62c9";
    };
    "has@npm:1.0.3" = {
      name = "has";
      reference = "npm:1.0.3";
      linkType = "HARD";
      outputName = "has-1.0.3-b7f00631c1";
      outputHash = "3e8c4d87ccd9c160d61a5db829b5fb647acac79e482476c857d5d1dc580517c6a77cf84337808f28361f6263008ce1ce5aff44407bd9241af93c623ef8d8d4f1";
      flatName = "has";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^1.0.3";
      checksum = "9/3e8c4d87ccd9c160d61a5db829b5fb647acac79e482476c857d5d1dc580517c6a77cf84337808f28361f6263008ce1ce5aff44407bd9241af93c623ef8d8d4f1";
      dependencies = {
        "function-bind" = packages."function-bind@npm:1.1.1";
      };
    };
    "http-errors@npm:2.0.0" = {
      name = "http-errors";
      reference = "npm:2.0.0";
      linkType = "HARD";
      outputName = "http-errors-2.0.0-3f1c503428";
      outputHash = "4ca64437169c64e448700bfc07ebaf5555bc0bb5c0880ab171a20312580af586f0c9f1bd5e9047336c84b4a31ade801ca7fe8c1c7e1d654f4ea9d5dee71dbb3c";
      flatName = "http-errors";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:2.0.0";
      checksum = "9/4ca64437169c64e448700bfc07ebaf5555bc0bb5c0880ab171a20312580af586f0c9f1bd5e9047336c84b4a31ade801ca7fe8c1c7e1d654f4ea9d5dee71dbb3c";
      dependencies = {
        "depd" = packages."depd@npm:2.0.0";
        "inherits" = packages."inherits@npm:2.0.4";
        "setprototypeof" = packages."setprototypeof@npm:1.2.0";
        "statuses" = packages."statuses@npm:2.0.1";
        "toidentifier" = packages."toidentifier@npm:1.0.1";
      };
    };
    "iconv-lite@npm:0.4.24" = {
      name = "iconv-lite";
      reference = "npm:0.4.24";
      linkType = "HARD";
      outputName = "iconv-lite-0.4.24-c5c4ac6695";
      outputHash = "6cc23a171d6fe7c49ab89956a5f151dfc4db34b48b61cebe887051e35dbb9bebb25bf5e410e8c79efadfd8ed602a0f79f7d7814f77365841e0596c3136408eaf";
      flatName = "iconv-lite";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:0.4.24";
      checksum = "9/6cc23a171d6fe7c49ab89956a5f151dfc4db34b48b61cebe887051e35dbb9bebb25bf5e410e8c79efadfd8ed602a0f79f7d7814f77365841e0596c3136408eaf";
      dependencies = {
        "safer-buffer" = packages."safer-buffer@npm:2.1.2";
      };
    };
    "inherits@npm:2.0.4" = {
      name = "inherits";
      reference = "npm:2.0.4";
      linkType = "HARD";
      outputName = "inherits-2.0.4-c66b3957a0";
      outputHash = "ca76c7e45ec715bfe6c1dd67b780b9a15068f37b37ab56cf8b773537b2654238469a42950f5f4d301212755e7512be888f627752e778e1863d95cfedefc8b8bd";
      flatName = "inherits";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:2.0.4";
      checksum = "9/ca76c7e45ec715bfe6c1dd67b780b9a15068f37b37ab56cf8b773537b2654238469a42950f5f4d301212755e7512be888f627752e778e1863d95cfedefc8b8bd";
    };
    "ipaddr.js@npm:1.9.1" = {
      name = "ipaddr.js";
      reference = "npm:1.9.1";
      linkType = "HARD";
      outputName = "ipaddr.js-1.9.1-19ae7878b4";
      outputHash = "5b70543172617fc9b0456f153d197a4fe2df54d1c808ebb17ee85e3cbcb73cf7159a29288d2f10be294f796bcb0695940d7881f8532c3b2928c8f22a97779d00";
      flatName = "ipaddr.js";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:1.9.1";
      checksum = "9/5b70543172617fc9b0456f153d197a4fe2df54d1c808ebb17ee85e3cbcb73cf7159a29288d2f10be294f796bcb0695940d7881f8532c3b2928c8f22a97779d00";
    };
    "media-typer@npm:0.3.0" = {
      name = "media-typer";
      reference = "npm:0.3.0";
      linkType = "HARD";
      outputName = "media-typer-0.3.0-8674f8f0f5";
      outputHash = "21806e15268f71b2bbf35a57b5eb9a42e14be638b8b855e210fb90282744e622f9d232f34f1cf566dc487819ce66bbb8aa6568e3267f48b12e92e2ba679838ae";
      flatName = "media-typer";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:0.3.0";
      checksum = "9/21806e15268f71b2bbf35a57b5eb9a42e14be638b8b855e210fb90282744e622f9d232f34f1cf566dc487819ce66bbb8aa6568e3267f48b12e92e2ba679838ae";
    };
    "merge-descriptors@npm:1.0.1" = {
      name = "merge-descriptors";
      reference = "npm:1.0.1";
      linkType = "HARD";
      outputName = "merge-descriptors-1.0.1-615287aaa8";
      outputHash = "6c8d19415ddd30b17ebd8e4474897549915cb90bb1caa13bbc55cce27a72d377c289abd300a3e8c6c1a6d61c4ea1fbe297addf032a9d75cb8de2788bc8b9cb2c";
      flatName = "merge-descriptors";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:1.0.1";
      checksum = "9/6c8d19415ddd30b17ebd8e4474897549915cb90bb1caa13bbc55cce27a72d377c289abd300a3e8c6c1a6d61c4ea1fbe297addf032a9d75cb8de2788bc8b9cb2c";
    };
    "methods@npm:1.1.2" = {
      name = "methods";
      reference = "npm:1.1.2";
      linkType = "HARD";
      outputName = "methods-1.1.2-92f6fdb39b";
      outputHash = "4641d1eda8231aee6774d28a32249f1d4f04e2a58a86c4a968eed39d178d64594ed829301eb603356decc9bd423eacd68d6bde7874a291475800a1568e547d4e";
      flatName = "methods";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:~1.1.2";
      checksum = "9/4641d1eda8231aee6774d28a32249f1d4f04e2a58a86c4a968eed39d178d64594ed829301eb603356decc9bd423eacd68d6bde7874a291475800a1568e547d4e";
    };
    "mime-db@npm:1.40.0" = {
      name = "mime-db";
      reference = "npm:1.40.0";
      linkType = "HARD";
      outputName = "mime-db-1.40.0-a136b9af4b";
      outputHash = "c40c4b48bae02ed51d6f7c47e666f0c86be97335842bfdea295ec7737e4604e7089bc0c05a24fc927364a284745dfefc8af31aead711cc6f6684e920d037ddaf";
      flatName = "mime-db";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:1.40.0";
      checksum = "9/c40c4b48bae02ed51d6f7c47e666f0c86be97335842bfdea295ec7737e4604e7089bc0c05a24fc927364a284745dfefc8af31aead711cc6f6684e920d037ddaf";
    };
    "mime-db@npm:1.52.0" = {
      name = "mime-db";
      reference = "npm:1.52.0";
      linkType = "HARD";
      outputName = "mime-db-1.52.0-b5371d6fd2";
      outputHash = "95baf687a3f14ff2cc433e30dea5c4931c7f4b67059d44a0098cfb833858cad63ec13c20f98762bddd088c4e9dac6d95862db1ea9d3fe3fa68f57b69a325000d";
      flatName = "mime-db";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:1.52.0";
      checksum = "9/95baf687a3f14ff2cc433e30dea5c4931c7f4b67059d44a0098cfb833858cad63ec13c20f98762bddd088c4e9dac6d95862db1ea9d3fe3fa68f57b69a325000d";
    };
    "mime-types@npm:2.1.24" = {
      name = "mime-types";
      reference = "npm:2.1.24";
      linkType = "HARD";
      outputName = "mime-types-2.1.24-b1aaaae895";
      outputHash = "12f4b25653a1ebdca03c45cadc4792f448f71734227e6999ae2faa464ccc4c9b93a0a48363c73c26506271ffa60622410ddec8ef800c3d56efe679db05060b2f";
      flatName = "mime-types";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:~2.1.24";
      checksum = "9/12f4b25653a1ebdca03c45cadc4792f448f71734227e6999ae2faa464ccc4c9b93a0a48363c73c26506271ffa60622410ddec8ef800c3d56efe679db05060b2f";
      dependencies = {
        "mime-db" = packages."mime-db@npm:1.40.0";
      };
    };
    "mime-types@npm:2.1.35" = {
      name = "mime-types";
      reference = "npm:2.1.35";
      linkType = "HARD";
      outputName = "mime-types-2.1.35-dd9ea9f3e2";
      outputHash = "51e3b38d1b1b83da082f7c29042bcb22036101346394696b7643ef5da27ebf6bf71643bd45225ee75e4ea2836213780efc8c3dcd2055c84b49eb0afc061419d0";
      flatName = "mime-types";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^2.1.12";
      checksum = "9/51e3b38d1b1b83da082f7c29042bcb22036101346394696b7643ef5da27ebf6bf71643bd45225ee75e4ea2836213780efc8c3dcd2055c84b49eb0afc061419d0";
      dependencies = {
        "mime-db" = packages."mime-db@npm:1.52.0";
      };
    };
    "mime@npm:1.6.0" = {
      name = "mime";
      reference = "npm:1.6.0";
      linkType = "HARD";
      outputName = "mime-1.6.0-60ae95038a";
      outputHash = "d54c5e4de47046306425767290edaaefc6964fec09960c7df4a1f429f672b6651a13b01724180c698a0f5f0af556a81494d0380404a23da29460716f8454d6e0";
      flatName = "mime";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:1.6.0";
      checksum = "9/d54c5e4de47046306425767290edaaefc6964fec09960c7df4a1f429f672b6651a13b01724180c698a0f5f0af556a81494d0380404a23da29460716f8454d6e0";
      bin = {
        "mime" = "cli.js";
      };
    };
    "ms@npm:2.0.0" = {
      name = "ms";
      reference = "npm:2.0.0";
      linkType = "HARD";
      outputName = "ms-2.0.0-9e1101a471";
      outputHash = "de027828fc294bd9673f72caecf73f50eac7baf28a0dec371de03600a0aa5a891b0cb7f84a45071eac306c9dd260aed8e2174695cf3a99eaa37f663871241da9";
      flatName = "ms";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:2.0.0";
      checksum = "9/de027828fc294bd9673f72caecf73f50eac7baf28a0dec371de03600a0aa5a891b0cb7f84a45071eac306c9dd260aed8e2174695cf3a99eaa37f663871241da9";
    };
    "ms@npm:2.1.3" = {
      name = "ms";
      reference = "npm:2.1.3";
      linkType = "HARD";
      outputName = "ms-2.1.3-81ff3cfac1";
      outputHash = "78c12f6b473a022ebacc393fc14b76fe40b8feda7218124b86c4684e440e10377a063bec1d3902df1f74714f02b74b36ad7d3a6de9e2fbffa26fc29e5ce018fc";
      flatName = "ms";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:2.1.3";
      checksum = "9/78c12f6b473a022ebacc393fc14b76fe40b8feda7218124b86c4684e440e10377a063bec1d3902df1f74714f02b74b36ad7d3a6de9e2fbffa26fc29e5ce018fc";
    };
    "negotiator@npm:0.6.3" = {
      name = "negotiator";
      reference = "npm:0.6.3";
      linkType = "HARD";
      outputName = "negotiator-0.6.3-9d50e36171";
      outputHash = "d8e3b42d99638b1f363ce114c98e6906ade395c230058e50644417bd398b01381133dbca4bc49f30f6b1c93254e4b5a2d50cc47adcdabf2a8476b6f16311ad5d";
      flatName = "negotiator";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:0.6.3";
      checksum = "9/d8e3b42d99638b1f363ce114c98e6906ade395c230058e50644417bd398b01381133dbca4bc49f30f6b1c93254e4b5a2d50cc47adcdabf2a8476b6f16311ad5d";
    };
    "object-inspect@npm:1.12.3" = {
      name = "object-inspect";
      reference = "npm:1.12.3";
      linkType = "HARD";
      outputName = "object-inspect-1.12.3-1e7d20f5ff";
      outputHash = "052c374ab0a4c85201480374c1039dddac0aaa8ef0fcbe1b04026f4c832c5632db6cb63617d6403b2b9dca08d4302d781aeb6c4d0260de4a84118ecaf1b5ebda";
      flatName = "object-inspect";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^1.9.0";
      checksum = "9/052c374ab0a4c85201480374c1039dddac0aaa8ef0fcbe1b04026f4c832c5632db6cb63617d6403b2b9dca08d4302d781aeb6c4d0260de4a84118ecaf1b5ebda";
    };
    "on-finished@npm:2.4.1" = {
      name = "on-finished";
      reference = "npm:2.4.1";
      linkType = "HARD";
      outputName = "on-finished-2.4.1-907af70f88";
      outputHash = "93ad68cf985df7d5263acef0302610a63f5d28840054b8d9a085776427beec4c7ce5518274c46b302eefd43747e81f6bb7df7dc4a2a2b345c0c49f31ad344385";
      flatName = "on-finished";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:2.4.1";
      checksum = "9/93ad68cf985df7d5263acef0302610a63f5d28840054b8d9a085776427beec4c7ce5518274c46b302eefd43747e81f6bb7df7dc4a2a2b345c0c49f31ad344385";
      dependencies = {
        "ee-first" = packages."ee-first@npm:1.1.1";
      };
    };
    "parseurl@npm:1.3.3" = {
      name = "parseurl";
      reference = "npm:1.3.3";
      linkType = "HARD";
      outputName = "parseurl-1.3.3-1542397e00";
      outputHash = "cbd2f45d9ab7fe80e5a742ff88fdedcfae00a32b1e6cca174c4d5c11b9480d0dde9a22b5e9505da44734f047e7cea8457508fced54067b870595a7938d29b467";
      flatName = "parseurl";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:~1.3.3";
      checksum = "9/cbd2f45d9ab7fe80e5a742ff88fdedcfae00a32b1e6cca174c4d5c11b9480d0dde9a22b5e9505da44734f047e7cea8457508fced54067b870595a7938d29b467";
    };
    "path-to-regexp@npm:0.1.7" = {
      name = "path-to-regexp";
      reference = "npm:0.1.7";
      linkType = "HARD";
      outputName = "path-to-regexp-0.1.7-2605347373";
      outputHash = "65caab5a929dda7ae7f6ab3be871a82390317291271694dea898eea5fdcc232ae7fd197a76a3cda4bd6dcef8d82e582578e02eb7d5fa659df0f4d33a53c9753f";
      flatName = "path-to-regexp";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:0.1.7";
      checksum = "9/65caab5a929dda7ae7f6ab3be871a82390317291271694dea898eea5fdcc232ae7fd197a76a3cda4bd6dcef8d82e582578e02eb7d5fa659df0f4d33a53c9753f";
    };
    "proxy-addr@npm:2.0.7" = {
      name = "proxy-addr";
      reference = "npm:2.0.7";
      linkType = "HARD";
      outputName = "proxy-addr-2.0.7-dae6552872";
      outputHash = "c03f00d8f882b97636262d0ae7da0c502325474ea215f21b4f0664ad8f40f49d2071b52c18257d011338be3db21ca65a6e8cbc0d95fb23efc00516ce9ee37c27";
      flatName = "proxy-addr";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:~2.0.7";
      checksum = "9/c03f00d8f882b97636262d0ae7da0c502325474ea215f21b4f0664ad8f40f49d2071b52c18257d011338be3db21ca65a6e8cbc0d95fb23efc00516ce9ee37c27";
      dependencies = {
        "forwarded" = packages."forwarded@npm:0.2.0";
        "ipaddr.js" = packages."ipaddr.js@npm:1.9.1";
      };
    };
    "proxy-from-env@npm:1.1.0" = {
      name = "proxy-from-env";
      reference = "npm:1.1.0";
      linkType = "HARD";
      outputName = "proxy-from-env-1.1.0-c13d07f26b";
      outputHash = "0bba2ef7c8374b384e94e4477764e53df66fcdfa7d19e2c4a063cb39eea979c139ce13981970223665422e72b7d149609a927046e2e40ab340b84d91af082591";
      flatName = "proxy-from-env";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^1.1.0";
      checksum = "9/0bba2ef7c8374b384e94e4477764e53df66fcdfa7d19e2c4a063cb39eea979c139ce13981970223665422e72b7d149609a927046e2e40ab340b84d91af082591";
    };
    "qs@npm:6.11.0" = {
      name = "qs";
      reference = "npm:6.11.0";
      linkType = "HARD";
      outputName = "qs-6.11.0-caf1bc9dea";
      outputHash = "337966e2e957a7d2a69821c528f3d18a8b346ddb0f16cc08d11c6206aed3b6624927781ff437aa3909e54ad32ebdee2c5396ad4094b1c722760774f7082f6124";
      flatName = "qs";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:6.11.0";
      checksum = "9/337966e2e957a7d2a69821c528f3d18a8b346ddb0f16cc08d11c6206aed3b6624927781ff437aa3909e54ad32ebdee2c5396ad4094b1c722760774f7082f6124";
      dependencies = {
        "side-channel" = packages."side-channel@npm:1.0.4";
      };
    };
    "range-parser@npm:1.2.1" = {
      name = "range-parser";
      reference = "npm:1.2.1";
      linkType = "HARD";
      outputName = "range-parser-1.2.1-1a470fa390";
      outputHash = "fc96933398c1a37a5c0c02bfc84ae171fa71b6f7b3d4360f84c9faeff5f43f29ebc59b404eab9af00073bb03a9717e05f8c46cd191524b6aefc72f227bad54d5";
      flatName = "range-parser";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:~1.2.1";
      checksum = "9/fc96933398c1a37a5c0c02bfc84ae171fa71b6f7b3d4360f84c9faeff5f43f29ebc59b404eab9af00073bb03a9717e05f8c46cd191524b6aefc72f227bad54d5";
    };
    "raw-body@npm:2.5.1" = {
      name = "raw-body";
      reference = "npm:2.5.1";
      linkType = "HARD";
      outputName = "raw-body-2.5.1-9dd1d9fff9";
      outputHash = "b5e41c0e7213e078f045a2b2397eb35665e952ad5176ff7462b740f7c7730b3d47d496ab2b1dd31ed36f8ffed41291cf93b035516403e0babea72c42d039b66b";
      flatName = "raw-body";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:2.5.1";
      checksum = "9/b5e41c0e7213e078f045a2b2397eb35665e952ad5176ff7462b740f7c7730b3d47d496ab2b1dd31ed36f8ffed41291cf93b035516403e0babea72c42d039b66b";
      dependencies = {
        "bytes" = packages."bytes@npm:3.1.2";
        "http-errors" = packages."http-errors@npm:2.0.0";
        "iconv-lite" = packages."iconv-lite@npm:0.4.24";
        "unpipe" = packages."unpipe@npm:1.0.0";
      };
    };
    "safe-buffer@npm:5.2.1" = {
      name = "safe-buffer";
      reference = "npm:5.2.1";
      linkType = "HARD";
      outputName = "safe-buffer-5.2.1-3481c8aa9b";
      outputHash = "da8a21b3336a21c152eb3ba8ab41acde5772644f026d4b6e5f9fd8afa4f0cf407c113b19a362580fab9aea8beea295465432fc7684f9ff38aac559bb1b5528cd";
      flatName = "safe-buffer";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:5.2.1";
      checksum = "9/da8a21b3336a21c152eb3ba8ab41acde5772644f026d4b6e5f9fd8afa4f0cf407c113b19a362580fab9aea8beea295465432fc7684f9ff38aac559bb1b5528cd";
    };
    "safer-buffer@npm:2.1.2" = {
      name = "safer-buffer";
      reference = "npm:2.1.2";
      linkType = "HARD";
      outputName = "safer-buffer-2.1.2-8d5c0b705e";
      outputHash = "d4199666e9e792968c0b88c2c35dd400f56d3eecb9affbcf5207922822eadf30cc06995bae3c5d0a653851bbd40fc0af578bf046bbf734199ce22433ba4da659";
      flatName = "safer-buffer";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:>= 2.1.2 < 3";
      checksum = "9/d4199666e9e792968c0b88c2c35dd400f56d3eecb9affbcf5207922822eadf30cc06995bae3c5d0a653851bbd40fc0af578bf046bbf734199ce22433ba4da659";
    };
    "send@npm:0.18.0" = {
      name = "send";
      reference = "npm:0.18.0";
      linkType = "HARD";
      outputName = "send-0.18.0-faadf6353f";
      outputHash = "670f134b35017d77ae82b02f04f5529651c4970887a5ffc581f003ed3858f8bda991eb1213e3b94f3c98acdcfc6a16cf83b58d330892662efe41d1d0d7993838";
      flatName = "send";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:0.18.0";
      checksum = "9/670f134b35017d77ae82b02f04f5529651c4970887a5ffc581f003ed3858f8bda991eb1213e3b94f3c98acdcfc6a16cf83b58d330892662efe41d1d0d7993838";
      dependencies = {
        "depd" = packages."depd@npm:2.0.0";
        "destroy" = packages."destroy@npm:1.2.0";
        "encodeurl" = packages."encodeurl@npm:1.0.2";
        "escape-html" = packages."escape-html@npm:1.0.3";
        "etag" = packages."etag@npm:1.8.1";
        "fresh" = packages."fresh@npm:0.5.2";
        "http-errors" = packages."http-errors@npm:2.0.0";
        "mime" = packages."mime@npm:1.6.0";
        "ms" = packages."ms@npm:2.1.3";
        "on-finished" = packages."on-finished@npm:2.4.1";
        "range-parser" = packages."range-parser@npm:1.2.1";
        "statuses" = packages."statuses@npm:2.0.1";
        "debug" = packages."debug@virtual:759fd14db92b54abdb7afb3d21dbf8d50f1a5c59c96cd3f963ce3e3ed063bdb801142fae5f01cc81fb79f7ddc13b7c31a9deb9d5a9cfa48ec107f83de8f7f40e#npm:2.6.9";
      };
    };
    "serve-static@npm:1.15.0" = {
      name = "serve-static";
      reference = "npm:1.15.0";
      linkType = "HARD";
      outputName = "serve-static-1.15.0-86c81879f5";
      outputHash = "38b4b126ef7497103b0466c1b876e2ad9732d3a32a905ef6b54681525802a2defba6e8e48c136f68c666e48f8c2dc869d24060b0a83f1dbdf724632cccf072fe";
      flatName = "serve-static";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:1.15.0";
      checksum = "9/38b4b126ef7497103b0466c1b876e2ad9732d3a32a905ef6b54681525802a2defba6e8e48c136f68c666e48f8c2dc869d24060b0a83f1dbdf724632cccf072fe";
      dependencies = {
        "encodeurl" = packages."encodeurl@npm:1.0.2";
        "escape-html" = packages."escape-html@npm:1.0.3";
        "parseurl" = packages."parseurl@npm:1.3.3";
        "send" = packages."send@npm:0.18.0";
      };
    };
    "setprototypeof@npm:1.2.0" = {
      name = "setprototypeof";
      reference = "npm:1.2.0";
      linkType = "HARD";
      outputName = "setprototypeof-1.2.0-0fedbdcd3a";
      outputHash = "ba389f4722581d9070df0a323a29501254594a97fee0e9308e73372f9856dbdb37fff71a0fef1e31c48901384544260d12925b791477e0101d7a68a6e28c23cf";
      flatName = "setprototypeof";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:1.2.0";
      checksum = "9/ba389f4722581d9070df0a323a29501254594a97fee0e9308e73372f9856dbdb37fff71a0fef1e31c48901384544260d12925b791477e0101d7a68a6e28c23cf";
    };
    "side-channel@npm:1.0.4" = {
      name = "side-channel";
      reference = "npm:1.0.4";
      linkType = "HARD";
      outputName = "side-channel-1.0.4-e1f38b9e06";
      outputHash = "d712a4e682471c1a1c7bf9294a8bb0f066566e016de11fdb01ae0c0ebf8102c97cc2b2d3b0264ca377eb2d3444bf4c06909392c518a162f047b7444608e0e9a2";
      flatName = "side-channel";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^1.0.4";
      checksum = "9/d712a4e682471c1a1c7bf9294a8bb0f066566e016de11fdb01ae0c0ebf8102c97cc2b2d3b0264ca377eb2d3444bf4c06909392c518a162f047b7444608e0e9a2";
      dependencies = {
        "call-bind" = packages."call-bind@npm:1.0.2";
        "get-intrinsic" = packages."get-intrinsic@npm:1.2.0";
        "object-inspect" = packages."object-inspect@npm:1.12.3";
      };
    };
    "statuses@npm:2.0.1" = {
      name = "statuses";
      reference = "npm:2.0.1";
      linkType = "HARD";
      outputName = "statuses-2.0.1-81d2b97fee";
      outputHash = "a7e9d41901245a442e77b339f715d77ac113c03ab9434d9f81ae45d75ed3437d9824e601ae1a834ad3e471ae3fc78d3c00decec5e826c91552a58d4c38833ecf";
      flatName = "statuses";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:2.0.1";
      checksum = "9/a7e9d41901245a442e77b339f715d77ac113c03ab9434d9f81ae45d75ed3437d9824e601ae1a834ad3e471ae3fc78d3c00decec5e826c91552a58d4c38833ecf";
    };
    "terraform-vault-http-backend@workspace:." = {
      name = "terraform-vault-http-backend";
      reference = "workspace:.";
      linkType = "SOFT";
      outputName = "terraform-vault-http-backend-1.0.0-20690b727f";
      src = ./.;
      shouldBeUnplugged = true;
      flatName = "terraform-vault-http-backend";
      languageName = "unknown";
      scope = null;
      descriptorRange = "workspace:.";
      bin = {
        "terraform-vault-http-backend" = "index.js";
      };
      dependencies = {
        "axios" = packages."axios@npm:1.3.2";
        "body-parser" = packages."body-parser@npm:1.20.1";
        "express" = packages."express@npm:4.18.2";
        "express-async-errors" = packages."express-async-errors@virtual:20690b727f8f63037236fdd078fbea158240df1898ed7ac0a357d6b9ddd8d82251ae615c7402ceaf348c08556c6e72765f7c21f0bb478e101f19e0e4984d871e#npm:3.1.1";
      };
    };
    "toidentifier@npm:1.0.1" = {
      name = "toidentifier";
      reference = "npm:1.0.1";
      linkType = "HARD";
      outputName = "toidentifier-1.0.1-f759712599";
      outputHash = "ed889234ceb442c0d5f87ab3f2a8fc0679800baa41766c0d9ce1bb82c700052fd6cf5d1656e1304de13d7a7d5974962fedc1bbe9a0e4686c3d8743c716c7dd5f";
      flatName = "toidentifier";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:1.0.1";
      checksum = "9/ed889234ceb442c0d5f87ab3f2a8fc0679800baa41766c0d9ce1bb82c700052fd6cf5d1656e1304de13d7a7d5974962fedc1bbe9a0e4686c3d8743c716c7dd5f";
    };
    "type-is@npm:1.6.18" = {
      name = "type-is";
      reference = "npm:1.6.18";
      linkType = "HARD";
      outputName = "type-is-1.6.18-6dee4d4961";
      outputHash = "1cf58e1d0c2129201bee6abe8029f5dda621f86a1094955b6510c9baf879a45f725b2e19c7dc1f04a623a0edd8f3cc39cc4d4899287c805b6b1177c961f46564";
      flatName = "type-is";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:~1.6.18";
      checksum = "9/1cf58e1d0c2129201bee6abe8029f5dda621f86a1094955b6510c9baf879a45f725b2e19c7dc1f04a623a0edd8f3cc39cc4d4899287c805b6b1177c961f46564";
      dependencies = {
        "media-typer" = packages."media-typer@npm:0.3.0";
        "mime-types" = packages."mime-types@npm:2.1.24";
      };
    };
    "unpipe@npm:1.0.0" = {
      name = "unpipe";
      reference = "npm:1.0.0";
      linkType = "HARD";
      outputName = "unpipe-1.0.0-2ed2a3c2bf";
      outputHash = "0504c357ea2fced264cd144bb1c3e44515a22ea8003eb3c35d3dabcb67181b023febec6bfa6fc6d863877bc556ae5939ede1c26d81a7dfd4a8f06b16bd091ea5";
      flatName = "unpipe";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:1.0.0";
      checksum = "9/0504c357ea2fced264cd144bb1c3e44515a22ea8003eb3c35d3dabcb67181b023febec6bfa6fc6d863877bc556ae5939ede1c26d81a7dfd4a8f06b16bd091ea5";
    };
    "utils-merge@npm:1.0.1" = {
      name = "utils-merge";
      reference = "npm:1.0.1";
      linkType = "HARD";
      outputName = "utils-merge-1.0.1-363bbdfbca";
      outputHash = "b72b8d7a0f7d63a9b1ced39a44b292994111c93cf9c4da8a561e4fe0d0232af7217a53d5aae3a950fb7ab6f423baf3e0d2d7c7c33dd6c4ec78d0a3c720ee6adb";
      flatName = "utils-merge";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:1.0.1";
      checksum = "9/b72b8d7a0f7d63a9b1ced39a44b292994111c93cf9c4da8a561e4fe0d0232af7217a53d5aae3a950fb7ab6f423baf3e0d2d7c7c33dd6c4ec78d0a3c720ee6adb";
    };
    "vary@npm:1.1.2" = {
      name = "vary";
      reference = "npm:1.1.2";
      linkType = "HARD";
      outputName = "vary-1.1.2-b49f70ae63";
      outputHash = "b1db20d4be443aec48b8efab73386f83d947b7033b6b2f5a0c7ba4a1f9bc0200cb4cb396712468761f8edfe48dd68a6fdee7c65689b90937a2d767c714d25883";
      flatName = "vary";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:~1.1.2";
      checksum = "9/b1db20d4be443aec48b8efab73386f83d947b7033b6b2f5a0c7ba4a1f9bc0200cb4cb396712468761f8edfe48dd68a6fdee7c65689b90937a2d767c714d25883";
    };
  };
in
packages
